### PR TITLE
Fix version collate returning incorrect value when last character is a delimiter

### PR DESCRIPTION
**Pull request by Micah-Kolide**
There's a small bug in the version collations where the difference in length of the versions is returned when the next character of the longer version is a delimiter, which it should return any segment value difference before length difference.

### CODE REVIEW

**Review by directionless — COMMENTED** [review]
Can you add a test case?

**Comment by Micah-Kolide** [comment]
> Can you add a test case?

Added them. There's not much this fix changes, so I figured that only a couple of tests for this change would be needed, but I can add more if you'd like.

**Comment by directionless** [comment]
It's worth adding a test case for this failure. After all, we missed it last time

**Comment by Micah-Kolide** [comment]
> It's worth adding a test case for this failure. After all, we missed it last time

Perhaps I'm a little confused. Are you reaffirming the test cases value, or noting that I should add additional cases for this failure? I meant in my last message that I have added test cases for this failure, but only a couple.

**Review by directionless — APPROVED** [review]
Oh, I misunderstood your comment. I see the test case now

**Pull request merged**
