### PR TITLE
Add Windows support to firefox_addons table

### PR DESCRIPTION
**Pull request by FritzX6**
## What is being changed?
The table `firefox_addons` currently only has support for Chrome and Linux, this change adds support for Windows by specifying the equivalent path of the `extensions.json` file.

The default path on Windows is located at:
```shell
C:\Users\%\AppData\Roaming\Mozilla\Firefox\Profiles\%\extensions.json
```

## 

## How has this been tested?
**Tested platforms:**
- [x] Windows
- [ ] Linux
- [x] macOS

I built osqueryd from source on the following 2 devices (I omitted Linux as my test device was too anemic to build on):

### Windows Device:

**Hardware Info:**
```SQL
osquery> select * from system_info;
          cpu_type = x86_64
         cpu_brand = Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
cpu_physical_cores = 2
 cpu_logical_cores = 4
     cpu_microcode = 198
   physical_memory = 7896395776
   hardware_vendor = LENOVO
    hardware_model = 20FQ005XUS
```

**OS Info**
```SQL
osquery> select * from os_version;
         name = Microsoft Windows 10 Pro
      version = 10.0.17763
        major = 10
        minor = 0
        build = 17763
     platform = windows
     codename = Microsoft Windows 10 Pro
 install_date = 20190312235255.000000-300
```

### macOS

**Hardware Info:**
```SQL
osquery> select * from system_info;
              uuid = E664D52B-***
          cpu_type = x86_64h
       cpu_subtype = Intel x86-64h Haswell
         cpu_brand = Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
cpu_physical_cores = 8
 cpu_logical_cores = 16
   physical_memory = 34359738368
   hardware_vendor = Apple Inc.
    hardware_model = iMacPro1,1
  hardware_version = 1.0
   hardware_serial = C02***
```
**OS Info**
```SQL
osquery> select * from os_version;
         name = Mac OS X
      version = 10.15.2
        major = 10
        minor = 15
        patch = 2
        build = 19C57
     platform = darwin
```

## Test Output:
I then ran queries against the modified table locally on these devices as demonstrated below, for brevity's sake, only the Windows output is included but both devices returned complete results:

```SQL
osquery> select * from firefox_addons;
+------+---------------------------------+----------------------------------------+---------------------------------------------+-----------+----------+----------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+----------+------------+--------+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| uid  | name                            | identifier                             | creator                                     | type      | version  | description                                                                                                                      | source_url                                                                                                                                                                            | visible | active | disabled | autoupdate | native | location            | path                                                                                                                                           |
+------+---------------------------------+----------------------------------------+---------------------------------------------+-----------+----------+----------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+----------+------------+--------+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| 1001 | LastPass: Free Password Manager | support@lastpass.com                   | LastPass                                    | extension | 4.40.1.2 | Last Password you will ever need                                                                                                 | https://addons.mozilla.org/firefox/downloads/file/3484323/lastpass_password_manager-4.40.1.2-fx.xpi?src=dp-btn-primary                                                                | 1       | 1      | 0        | 1          |        | app-profile         | C:\Users\kolide-lenovo\AppData\Roaming\Mozilla\Firefox\Profiles\fy6ep3pc.default-release\extensions\support@lastpass.com.xpi                   |
| 1001 | 1Password X – Password Manager  | {d634138d-c276-4fc8-924b-40a0ea21d284} | AgileBits                                   | extension | 1.17.0   | The best way to experience 1Password in your browser. Easily sign in to sites, generate passwords, and store secure information. | https://addons.cdn.mozilla.net/user-media/addons/950528/1password_x_password_manager-1.17.0-fx.xpi?filehash=sha256%3Ae3c54fcbdb807465d9eb31f99d1e2678545e133ae0131fad9828c3fadfa0d135 | 1       | 1      | 0        | 1          |        | app-profile         | C:\Users\kolide-lenovo\AppData\Roaming\Mozilla\Firefox\Profiles\fy6ep3pc.default-release\extensions\{d634138d-c276-4fc8-924b-40a0ea21d284}.xpi |
| 1001 | Form Autofill                   | formautofill@mozilla.org               | null                                        | extension | 1.0      |                                                                                                                                  | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-system-defaults | C:\Program Files\Mozilla Firefox\browser\features\formautofill@mozilla.org.xpi                                                                 |
| 1001 | Firefox Screenshots             | screenshots@mozilla.org                | Mozilla <screenshots-feedback@mozilla.com>  | extension | 39.0.0   | Take clips and screenshots from the Web and save them temporarily or permanently.                                                | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-system-defaults | C:\Program Files\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi                                                                  |
| 1001 | WebCompat Reporter              | webcompat-reporter@mozilla.org         | Thomas Wisniewski <twisniewski@mozilla.com> | extension | 1.1.0    | Report site compatibility issues on webcompat.com                                                                                | null                                                                                                                                                                                  | 1       | 0      | 1        | 1          |        | app-system-defaults | C:\Program Files\Mozilla Firefox\browser\features\webcompat-reporter@mozilla.org.xpi                                                           |
| 1001 | Web Compat                      | webcompat@mozilla.org                  | null                                        | extension | 6.4.0    | Urgent post-release fixes for web compatibility.                                                                                 | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-system-defaults | C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi                                                                    |
| 1001 | DoH Roll-Out                    | doh-rollout@mozilla.org                | null                                        | extension | 1.3.0    | Mozilla add-on that supports the roll-out of DoH                                                                                 | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-system-defaults | C:\Program Files\Mozilla Firefox\browser\features\doh-rollout@mozilla.org.xpi                                                                  |
| 1001 | Default                         | default-theme@mozilla.org              | Mozilla                                     | theme     | 1.0      | A theme with the operating system color scheme.                                                                                  | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-builtin         | null                                                                                                                                           |
| 1001 | Light                           | firefox-compact-light@mozilla.org      | Mozilla                                     | theme     | 1.0      | A theme with a light color scheme.                                                                                               | null                                                                                                                                                                                  | 1       | 0      | 1        | 1          |        | app-builtin         | null                                                                                                                                           |
| 1001 | Dark                            | firefox-compact-dark@mozilla.org       | Mozilla                                     | theme     | 1.0      | A theme with a dark color scheme.                                                                                                | null                                                                                                                                                                                  | 1       | 0      | 1        | 1          |        | app-builtin         | null                                                                                                                                           |
| 1001 | Google                          | google@search.mozilla.org              | null                                        | extension | 1.0      | Google Search                                                                                                                    | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-builtin         | null                                                                                                                                           |
| 1001 | Amazon.com                      | amazondotcom@search.mozilla.org        | null                                        | extension | 1.1      | Amazon.com Search                                                                                                                | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-builtin         | null                                                                                                                                           |
| 1001 | Bing                            | bing@search.mozilla.org                | null                                        | extension | 1.0      | Bing. Search by Microsoft.                                                                                                       | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-builtin         | null                                                                                                                                           |
| 1001 | DuckDuckGo                      | ddg@search.mozilla.org                 | null                                        | extension | 1.0      | Search DuckDuckGo                                                                                                                | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-builtin         | null                                                                                                                                           |
| 1001 | eBay                            | ebay@search.mozilla.org                | null                                        | extension | 1.0      | eBay - Online auctions                                                                                                           | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-builtin         | null                                                                                                                                           |
| 1001 | Twitter                         | twitter@search.mozilla.org             | null                                        | extension | 1.0      | Realtime Twitter Search                                                                                                          | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-builtin         | null                                                                                                                                           |
| 1001 | Wikipedia (en)                  | wikipedia@search.mozilla.org           | null                                        | extension | 1.0      | Wikipedia, the Free Encyclopedia                                                                                                 | null                                                                                                                                                                                  | 1       | 1      | 0        | 1          |        | app-builtin         | null                                                                                                                                           |
+------+---------------------------------+----------------------------------------+---------------------------------------------+-----------+----------+----------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+----------+------------+--------+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
```

### CODE REVIEW

**Comment by FritzX6** [comment]
Looks like this is an already in-flight PR: #6163 though it appears some additional file changes to the `BUCK` and `CMAKElists.txt` files are necessary in that one.

Happy for this one to be closed as I didn't see it when I opened my PR.

**Comment by muffins** [comment]
@FritzX6 entirely up to you! I'd say let's see if we get a signed CLA on that PR first, and if we don't get a response in maybe a week or so let's just #movefast and go with yours?

**Comment by nmeocisco** [comment]
Looks like there are some hiccups involving the CLA that are unfortunately outside of my control, but I am perfectly happy to have this being merged over my PR. Feel free to close my PR and use this rather than waiting on me to get CLA approval.

Make sure that this handles UTF-8 okay, I encountered some issues with `readFile()` not reading the JSON file correctly. Most likely this is due to certain file operations in Windows not always reading binary properly unless explicitly specified. How you resolve this potential issue I will leave up to you.

**Comment by Smjert** [comment]
> Make sure that this handles UTF-8 okay, I encountered some issues with `readFile()` not reading the JSON file correctly. Most likely this is due to certain file operations in Windows not always reading binary properly unless explicitly specified. How you resolve this potential issue I will leave up to you.

I suspect that this issue could be involved: https://github.com/osquery/osquery/issues/5661

**Comment by muffins** [comment]
@nmeocisco thanks for letting us know!

@FritzX6 do you have any objections to adding in the try/catch as recommended? Otherwise I think we're good to go? 

```
  try {
    if (!readFile(path, json_data).ok()) {
      pt::read_json(path.string(), tree);
      return Status(1, "Could not read JSON from file");
    }
  } catch (const pt::json_parser::json_parser_error& e) {
    return Status(1, "Could not parse JSON from file");
  }
  return Status::success();
```

**Comment by muffins** [comment]
Looks like this also might need a `clang-format` before we can move forward.

**Comment by FritzX6** [comment]
> @nmeocisco thanks for letting us know!
> 
> @FritzX6 do you have any objections to adding in the try/catch as recommended? Otherwise I think we're good to go?
> 
> ```
>   try {
>     if (!readFile(path, json_data).ok()) {
>       pt::read_json(path.string(), tree);
>       return Status(1, "Could not read JSON from file");
>     }
>   } catch (const pt::json_parser::json_parser_error& e) {
>     return Status(1, "Could not parse JSON from file");
>   }
>   return Status::success();
> ```

@muffins No objections from me on that.

Also, you are right, I got stymied by the `clang-format`.

To use the format tool, I ended up having to squish my previous commits to restage all my changes _(no fun... but thank you very much to @directionless !)_. 

🤞 Fingers crossed it builds this time!

**Comment by directionless** [comment]
A bit of a call out -- the "try/catch" is a bit deeper than just that. Per @nmeocisco's comment, the old `readFile` call was munging utf-8, so this removes that in favor of doing the json parsing directly in `parseJSON`

**Pull request merged**
