### PR TITLE
Restore macOS `kernel_panics` table on modern macOS

### LINKED ISSUE #7215: Empty kernel_panics table after macOS 10.15
# Bug report
Looks like Osquery is not able to find and parse the kernel panic logs correctly in macOS 11.4.

### What operating system and version are you using?
version = 11.4
build = 20F71
platform = darwin

### What version of osquery are you using?
version = 4.9.0

### What steps did you take to reproduce the issue?
Trigger a Kernel Panic on a Mac machine (with macOS 11.4 installed.)
1. Reboot into software recovery mode. Disable SIP - `csrutil disable`
2. Reboot again.
3. Run - `sudo dtrace -w -n "BEGIN{ panic();}"`

### What did you expect to see?
`osqueryi --line "SELECT * from kernel_panics;"` shows kernel panics information.

### What did you see instead?
The query returns empty. 

I'm able to see the panic log files in this directory - `/Library/Logs/DiagnosticReports/ProxiedDevice-Bridge`. The file names are like `panic-full-2021-07-28-142855.0003.ips`.

### PR DESCRIPTION
**Pull request by mike-myers-tob**
Fixes #7215 by unwrapping a light layer of undocumented obfuscation (JSON) that Apple added to their semi-structured plaintext kernel panic log files up through macOS 10.15. Some columns don't appear to exist anymore, or might just be missing from my crash dump: `dependencies`, `last_unloaded`, etc.

- [x] attempt to read the `regsiters` column, but unfortunately the data is not there anymore (at least since macOS 10.14)
- [x] same for `module_backtrace` column, but unfortunately the data is not there anymore (at least since macOS 10.14)
- [x] test on M1 Mac
- [x] test on macOS 10.15
- [x] test on macOS 10.14
- [x] ~test on macOS 11.x~ (skipped, since the format in 10.15.6 and 12.3.1 are exactly the same)
- [x] clean up and clang-format

Example of table working to parse a crash dump:

```
mmyers@mmyerss-Mac build % ./osquery/osqueryi
Using a virtual database. Need help, type '.help'
osquery> .mode line
osquery> select * from kernel_panics;
            path = /Library/Logs/DiagnosticReports/Kernel-2022-05-05-173858.panic
            time = 2022-05-05 17:38:58.00 -0700
       registers = 
 frame_backtrace = 0xffffffe0735e3210 : 0xffffff8019c83e2d
module_backtrace = 
    dependencies = 
            name = dtrace
      os_version = 21E258
  kernel_version = Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    system_model = VMware7,1 (Mac-5F9802EFE386AA28)
          uptime = 779382986226
     last_loaded = |IOAVB!F 1040.6 (addr 0xffffff7fb2b2f000, size 77824)
   last_unloaded = 
```

### CODE REVIEW

**Comment by mike-myers-tob** [comment]
Interestingly, the kernel panic log format in macOS 12 is also the exact same format I just saw generated in macOS 10.15.7.

**Comment by mike-myers-tob** [comment]
The following content is just no longer present in panic logs. I will try to find when it was last present, but right now these just can't be filled in:

1. `registers` (Apple stopped capturing this in the log)
2. `module_backtrace` unless it is present only in certain circumstances. I only have one kernel panic I can create.
3. `dependencies` (same reason)

The `uptime` field isn't logged in a very accessible way on M1. It could _maybe_ be derived as a difference between `mach_absolute_time` and `Boot (Epoch Time)` or maybe that's not it either. In doubt, I just left it so it's blank on M1.

**Comment by mike-myers-tob** [comment]
A note for reviewers: macOS sweeps this log directory for kernel panic logs older than say, a week, and puts them in a subdirectory called `Retired`. Should osquery be looking there as well?

**Comment by mike-myers-tob** [comment]
Another interesting note: switching macOS system language to non-English does not appear to change the content of a kernel panic file, which is still created in English. So there's no internationalization concerns with this table.

**Comment by mike-myers-tob** [comment]
For reviewers who wish to test, see issue https://github.com/osquery/osquery/issues/7215 for instructions on creating your own panic log file, or [download one of mine](https://github.com/osquery/osquery/issues/7215#issuecomment-1138017571) and extract to the `/Library/Logs/DiagnosticReports/` directory.

**Comment by mike-myers-tob** [comment]
Bumping this to 5.5 until it gets reviewed but maybe after I get approver rights I can trade @sharvilshah for a review? :-)

**Review by sharvilshah — APPROVED** [review]
While I can't induce kernel panics on my machine (don't have access to disable SIP to do the dtrace panic() trick), tested with all the attached panic logs, and it works great!

**Comment by mike-myers-tob** [comment]
Thanks! I guess you have no more open PRs so I'll have to review the next one 😆

**Pull request merged**
