### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by garanews**
Parsed all repo with a regexp of common misspelled words and fixed.

### CODE REVIEW

**Comment by theopolis** [comment]
Hi @garanews, thanks for the PR. All of the code changes in `./libraries` are auto-generated content from third-party dependencies. We should not change this code even if there are typos. Do you mind updating this PR to remove these changes?

**Comment by garanews** [comment]
sure if you do, thanks, otherwise I can do.

**Comment by garanews** [comment]
@theopolis let me know if now is ok.

**Comment by sharvilshah** [comment]
This looks good, thanks @garanews!

**Review by theopolis — APPROVED** [review]

**Pull request merged**
