### PR TITLE
Fix for patches table documentation

### PR DESCRIPTION
**Pull request by srikwit**
https://github.com/osquery/osquery/issues/6350

To submit a PR please make sure to follow the next steps:

- [ ] Read the `CONTRIBUTING.md` guide on the root of the repo.
- [ ] Ensure the code is formatted building the `format_check` target,  
      if not move the committed files to the stage area,
      build the `format` target to format, then re-commit.
      More information is available on the wiki.
- [ ] Ensure your PR contains a single logical change.
- [ ] Ensure your PR contains tests for the changes you're submitting.
- [ ] Describe your changes with as much detail as you can.
- [ ] Link any issues this PR is related to.
- [ ] Remove the text above.

### CODE REVIEW

**Comment by theopolis** [comment]
Did we confirm this change is accurate?

**Comment by srikwit** [comment]
@theopolis I will be able to confirm by today evening. Sorry for the delay.

**Comment by srikwit** [comment]
No the change is not accurate after trying it out.

Here is the data from the patches table:
image

and the following is the data from the Hotfixes:
image

It can be seen that a patch which is installed might not have an install date in the patches table which contradicts the change. The original description is indeed accurate.

The same logic applies to the shared resources table:
image
and:
image

Hence, I believe the original descriptions can be retained.
I apologise for the wrong commit contents.
Thanks for reviewing the pull request.

**Comment by theopolis** [comment]
No problem at all, thanks for checking!

**Pull request closed without merging**
