### PR TITLE
Fixing port logic

### PR DESCRIPTION
**Pull request by Will-Low**
Per https://github.com/osql/osql/pull/7, this else if statement contains a bug where port should be appended to the Host header if not a standard port.

### CODE REVIEW

**Comment by grantseltzer** [comment]
@Will-Low Osquery work has been moved over to this repo, if you can fix the merge conflict we can get this merged and track our releases from here.

**Comment by theopolis** [comment]
Heads up, looks like this still is not rebased against the current master.

**Comment by theopolis** [comment]
Oh no, I don’t think the merge worked. Let me see if I can help.

**Comment by grantseltzer** [comment]
@theopolis What seems to be the issue?

**Comment by theopolis** [comment]
I made a mistake, when I was inspecting the changed-lines last night using the GH UI it seemed this branch pulled in overlapping changes.

**Pull request merged**
