### PR TITLE
Add git-lfs as dep for macOS build in documentation

### PR DESCRIPTION
**Pull request by daisukixci**
Add git-lfs as dependency in documentation because without it the `cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 ..` fails

Here the output, (I kept the all output if needed:
```bash
❯ mkdir build; cd buildcd
❯ cd osquery
❯ mkdir build; cd build
❯ cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 ..
...
-- Importing: source/icu
Submodule 'libraries/cmake/source/icu/src' (https://github.com/unicode-org/icu) registered for path 'src'
Cloning into '/Users/gaetan.piquenot/Workspace/tools/osquery/libraries/cmake/source/icu/src'...
From https://github.com/unicode-org/icu
 * branch            e2d85306162d3a0691b070b4f0a73e4012433444 -> FETCH_HEAD
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
Unable to checkout 'e2d85306162d3a0691b070b4f0a73e4012433444' in submodule path 'src'
CMake Error at libraries/cmake/source/modules/utils.cmake:55 (message):
  Failed to update the following git submodule:
  "/Users/gaetan.piquenot/tools/osquery/libraries/cmake/source/icu/src"
Call Stack (most recent call first):
  libraries/cmake/source/modules/utils.cmake:149 (initializeGitSubmodule)
  libraries/cmake/source/modules/Findicu.cmake:10 (importSourceSubmodule)
  libraries/cmake/source_migration/modules/Findicu.cmake:7 (include)
  CMakeLists.txt:152 (find_package)
  CMakeLists.txt:68 (importLibraries)
  CMakeLists.txt:192 (main)


-- Configuring incomplete, errors occurred!
See also "/Users/gaetan.piquenot/tools/osquery/build/CMakeFiles/CMakeOutput.log".
See also "/Users/gaetan.piquenot/tools/osquery/build/CMakeFiles/CMakeError.log".
```

### CODE REVIEW

**Comment by theopolis** [comment]
Good find!

**Comment by daisukixci** [comment]
I don't know, without it and the error was pretty explicit. Maybe I missed something

**Comment by directionless** [comment]
That's a weird disrepency. @Smjert @alessandrogario either of you know?

**Comment by theopolis** [comment]
This may only be a requirement if checking out https://github.com/unicode-org/icu for the first time. I was able to repro with a fresh clone of osquery.

**Pull request merged**
