### PR TITLE
Add AArch64 support on Linux

### PR DESCRIPTION
**Pull request by alessandrogario**
Import the following PR from @artemist: https://github.com/osquery/osquery/pull/6284

### CODE REVIEW

**Comment by mike-myers-tob** [comment]
Needs:
* rebase
* remove Buck scripts
* update the configuration files for linked library dependencies so they don't link to the versions on the local filesystem
* goal: building with Amazon Ubuntu 16 ARM-based AWS EC2 instance

**Comment by theopolis** [comment]
Is this work ongoing or paused, or maybe somewhere in between?

**Comment by alessandrogario** [comment]
> Is this work ongoing or paused, or maybe somewhere in between?

There is no one assigned to this yet, as I am finishing with BPF support. Any help appreciated to help this push forward!

**Comment by alessandrogario** [comment]
Following the last office hours, the next step before we can merge this and mark it as beta is just rebase on master and drop Buck support.

The lib configurations will be regenerated on Ubuntu 16 in additional PRs

**Comment by ozbenh** [comment]
Is anybody doing it or should I help ? Note: I have never touched this project, so will have to figure out what "drop Buck support" means, but I have customers who want this so...

**Pull request closed without merging**
