### PR TITLE
rocksdb: Do not fsync WAL writes

### PR DESCRIPTION
**Pull request by theopolis**
This addresses #7079 but makes logs more susceptible to data loss if a process crashes.

### CODE REVIEW

**Comment by directionless** [comment]
I'm unsure if this is the right approach. Or what the default is

**Comment by theopolis** [comment]
Yeah, I suspect this is the right start but it's not complete.

**Comment by Jimjazzz** [comment]
I have tested it, but still i see that .LOG files are created (it went up to around 200 files). 
I do not see a big improvement in IOPS (graphs for the last hour):
win4-io_ops

Attached here is the db of around the last hour:
[osquery.db (3).zip](https://github.com/osquery/osquery/files/6454401/osquery.db.3.zip)

Following is the evolution of db in terms of size and number of files:

win4-rocksdb_size
win4-rocksdb_files

**Comment by theopolis** [comment]
@Jimjazzz thank you so much for the testing effort. Would you mind trying once again with the latest changes: https://github.com/osquery/osquery/actions/runs/830071018

See my comment above about what is new.

**Comment by Jimjazzz** [comment]
Hi @theopolis , we have tested the latest build but i did not get the time to write back a report to you.

In terms of DB size and #files, i see a difference where this new build the number of LOG files is way more contained. Previous scenario grows up to 700 files, while the new one is around 100.
New build:
win4-rocksdb_files (1)

osquery v4.8.0
win12-rocksdb_files

New build:
win4-rocksdb_size (1)

osquery v4.8.0:
win12-rocksdb_size

I see that write IOPS are smaller, however i think that read spikes are bigger now:
New build:
win4-io_ops (1)

osquery v4.8.0
win12-io_ops

Also attached here the latest status of osquery.db (snapshot taken 5/14 16:28 GMT+2)
[osquery.db.zip](https://github.com/osquery/osquery/files/6479411/osquery.db.zip)

I can see a big improvement with respect to v4.6.0.2 , but not as big with the normal v4.8.0 release. Still, completely disabling WAL and sync gives me the best results.

However, i have been seeing that osquery seems to degrade after some time running when sending logs via TLS, as i can see event loss in our SIEM. I wonder if events buffering could be causing increased IOPS, since when we changed tls_logger_max_lines to 8192 we saw a good improvement on the situation. Now we are not reaching the limit in any flushm but we are still drastically lowering intervals and flush periods to see if we get any improvements.

**Comment by theopolis** [comment]
Ok thanks for testing. I think we should at least land this change. This essentially does not force an fsync after each WAL write.

**Review by zwass — APPROVED** [review]
Seems worth it for the limited improvement we get here. Let's make sure this is documented in the release notes.

**Pull request merged**
