### PR TITLE
Add --setns flag to run osqueryi in container namespace

### PR DESCRIPTION
**Pull request by amalone-scwx**
This change allows osqueryi to be run with `--setns=/proc/3333/ns/mnt` to run queries within a container namespace. Very useful for command-line scripts and testing tables for container support.
It's only compiled-in for linux targets.

### CODE REVIEW

**Comment by amalone-scwx** [comment]
I have changes for a corresponding `.setns` shell command, but figured it was better to keep them in separate PRs since they live in different parts of the codebase.

**Comment by theopolis** [comment]
This looks great and I think we should add it but there might be a cleaner way.

Would it be OK if we set the namespace before extensions were discovered/forked?

**Comment by amalone-scwx** [comment]
sure. like near the top of `startOsquery()`?

**Comment by theopolis** [comment]
I was going to suggest moving this into the `Initializer` class and having it work for both `osqueryd` and `osqueryi`. Is there some reason we want to keep it to shell-only?

**Comment by amalone-scwx** [comment]
The reason I was using the shell-only approach is the need for single threaded process.  However, if we can have it run early enough, it should work fine for either.  I will look at Initializer. Thanks.

**Comment by theopolis** [comment]
> The reason I was using the shell-only approach is the need for single threaded process.

This makes sense. If you want to be really sure that no additional threads have been created, make sure the namespace is entered before `registryAndPluginInit` is called.

**Comment by theopolis** [comment]
Ping, how is this coming along, do you need any help?

**Comment by amalone-scwx** [comment]
Sorry for the delay.  I spent some time on this today, but didn't finish.  I am rolling the `--setns` flag and `.setns` shell command into same PR.  Hopefully this week.

**Comment by amalone-scwx** [comment]
replaced by #6698

**Pull request closed without merging**
