### PR TITLE
Add support to AWS IMDSv2

### PR DESCRIPTION
**Pull request by sizins**
isEc2Instance API and ec2_instance_metadata table support AWS IMDSv2

### CODE REVIEW

**Comment by theopolis** [comment]
@sizins have you seen this other PR? https://github.com/osquery/osquery/pull/7084

**Comment by sizins** [comment]
> @sizins have you seen this other PR? #7084



> @sizins have you seen this other PR? #7084
@theopolis Checked the PR #7084, Felt I had a bit better solution.
This is my first commit and did not know if it is allowed to have 2 PRs for the same issue. 
Happy to close the PR if it breaks the process.

**Comment by mike-myers-tob** [comment]
> > @sizins have you seen this other PR? #7084
> 
> @theopolis Checked the PR #7084, Felt I had a bit better solution.
> This is my first commit and did not know if it is allowed to have 2 PRs for the same issue.
> Happy to close the PR if it breaks the process.

Your input is appreciated, but we'd prefer to close this PR and incorporate your suggestions into the other PR as part of the feedback discussion in the comments.

Also, can you explain the use-case for needing to cache the token?

**Comment by sizins** [comment]
> > > @sizins have you seen this other PR? #7084
> > 
> > 
> > @theopolis Checked the PR #7084, Felt I had a bit better solution.
> > This is my first commit and did not know if it is allowed to have 2 PRs for the same issue.
> > Happy to close the PR if it breaks the process.
> 
> Your input is appreciated, but we'd prefer to close this PR and incorporate your suggestions into the other PR as part of the feedback discussion in the comments.
> 
> Also, can you explain the use-case for needing to cache the token?

Token has an expiry time(TTL). It's better to use the same token till it expires.
Frequent generation of a new token can lead to exhaustion of random number generator used in token generation.

**Pull request closed without merging**
