### PR TITLE
[CI] Update macOS agent to 10.15 Catalina

### LINKED ISSUE #6707: Update Xcode version in Azure pipeline ahead of Oct 20th deprecation
# Task

@sharvilshah has found that Xcode versions 10.x, 11.0, 11.1, 11.4 will be deprecated on October 20th for the Azure pipeline macOS 10.15 Catalina image. We are currently trying to switch to the 10.15 macOS runner in https://github.com/osquery/osquery/pull/6680 and the change to the new Xcode might need to happen in that PR as well.

Ref: https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md

### PR DESCRIPTION
**Pull request by sharvilshah**
Updating the Azure Pipelines agent to use 10.15 Catalina image. This will also help with the EndpointSecurity work.

Here is the agent info: https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md

Closes #6707

### CODE REVIEW

**Comment by sharvilshah** [comment]
Screen Shot 2020-09-29 at 6 13 59 PM

It correctly picked up the new version (https://dev.azure.com/trailofbits/osquery/_build/results?buildId=3828&view=logs&j=7087e851-80cb-52bb-c098-0ae67b77f687&t=ffe76d4b-c1d9-4998-b70a-742ec95e6afe&l=6) but couple of macOS tests are failing. 

These are the same macOS tests that have failed on other older PRs.

**Comment by sharvilshah** [comment]
@alessandrogario @Smjert thoughts on this?

**Comment by Smjert** [comment]
> @alessandrogario @Smjert thoughts on this?

For the wifi table failure, could this be related? https://github.com/osquery/osquery/issues/6235

For the startup_items one, seems a simple suffix `/` difference?
```
[----------] 1 test from StartupItemsTests
21: [ RUN      ] StartupItemsTests.test_parse_startup_items
21: /Users/runner/work/1/s/osquery/tables/system/tests/darwin/startup_items_tests.cpp:35: Failure
21: Expected equality of these values:
21:   "/Applications/iTunes.app/Contents/MacOS/iTunesHelper.app/"
21:   results[0]["path"]
21:     Which is: "/Applications/iTunes.app/Contents/MacOS/iTunesHelper.app"
21: [  FAILED  ] StartupItemsTests.test_parse_startup_items (1 ms)
21: [----------] 1 test from StartupItemsTests (1 ms total)
```

For the integration tests we have:
```
83: [----------] 1 test from apps
83: [ RUN      ] apps.test_sanity
83: /Users/runner/work/1/s/tests/integration/tables/apps.cpp:55: Failure
83: Expected equality of these values:
83:   data1.size()
83:     Which is: 0
83:   1ul
83:     Which is: 1
83: [  FAILED  ] apps.test_sanity (1888 ms)
83: [----------] 1 test from apps (1888 ms total)
```

and the failing check is
https://github.com/osquery/osquery/blame/ecc5403903a75045a76aaaf4e2c4660d7ec8815e/tests/integration/tables/apps.cpp#L52-L55

So I guess that CI installations do not (always?) have Preview.app.

Then we have:
```
83: [----------] 1 test from browserPlugins
83: [ RUN      ] browserPlugins.test_sanity
83: /Users/runner/work/1/s/tests/integration/tables/browser_plugins.cpp:40: Failure
83: Value of: data.empty()
83:   Actual: true
83: Expected: false
83: [  FAILED  ] browserPlugins.test_sanity (4 ms)
83: [----------] 1 test from browserPlugins (4 ms total)
```

and the failing check is:
```
https://github.com/osquery/osquery/blob/ecc5403903a75045a76aaaf4e2c4660d7ec8815e/tests/integration/tables/browser_plugins.cpp#L39-L41
```

So here too probably not all installation contains a browser with plugins?

I'm not sure what is considered normal (the presence or possible absence).

**Comment by sharvilshah** [comment]
Somehow, after upgrading Xcode, `psutil` cannot be found (`81: ModuleNotFoundError: No module named 'psutil'
`) even though it's listed as a brew argument. 

Trying closing/reopening PR just in case.

**Comment by theopolis** [comment]
If you close and reopen the PR it will run all the tests again (this is a good trick for discovering flaky/transient issues).

**Comment by sharvilshah** [comment]
There is no way to ssh into the test runner/instance right?

The `DEBUG` target still can't find `psutil`:

```
2020-10-20T07:01:41.1869450Z       Start 81: tools_tests_testosqueryd
2020-10-20T07:01:41.1869910Z 
2020-10-20T07:01:41.1871780Z 81: Test command: /usr/local/Cellar/cmake/3.18.4/bin/cmake "-E" "env" "PYTHONPATH=/Users/runner/work/1/b/build/python_path" "/usr/local/Frameworks/Python.framework/Versions/3.8/bin/python3.8" "-u" "test_osqueryd.py" "--verbose" "--build" "/Users/runner/work/1/b/build" "--test-configs-dir" "/Users/runner/work/1/b/build/test_configs"
2020-10-20T07:01:41.1872960Z 81: Test timeout computed to be: 300
2020-10-20T07:01:41.5796140Z 81: Traceback (most recent call last):
2020-10-20T07:01:41.5796910Z 81:   File "test_osqueryd.py", line 18, in <module>
2020-10-20T07:01:41.5797250Z 81:     import test_base
2020-10-20T07:01:41.5797690Z 81:   File "/Users/runner/work/1/b/build/tools/tests/test_base.py", line 13, in <module>
2020-10-20T07:01:41.5798160Z 81:     import psutil
2020-10-20T07:01:41.5799270Z 81: ModuleNotFoundError: No module named 'psutil'
2020-10-20T07:01:41.5900990Z 81/83 Test #81: tools_tests_testosqueryd ..............................................***Failed    0.40 sec
2020-10-20T07:01:41.6310960Z test 82
2020-10-20T07:01:41.6311440Z       Start 82: tools_tests_testosqueryi
2020-10-20T07:01:41.6311750Z 
2020-10-20T07:01:41.6313930Z 82: Test command: /usr/local/Cellar/cmake/3.18.4/bin/cmake "-E" "env" "PYTHONPATH=/Users/runner/work/1/b/build/python_path" "/usr/local/Frameworks/Python.framework/Versions/3.8/bin/python3.8" "-u" "test_osqueryi.py" "--verbose" "--build" "/Users/runner/work/1/b/build" "--test-configs-dir" "/Users/runner/work/1/b/build/test_configs"
2020-10-20T07:01:41.6315140Z 82: Test timeout computed to be: 300
2020-10-20T07:01:41.7528000Z 82: Traceback (most recent call last):
2020-10-20T07:01:41.7528980Z 82:   File "test_osqueryi.py", line 17, in <module>
2020-10-20T07:01:41.7529780Z 82:     import test_base
2020-10-20T07:01:41.7530230Z 82:   File "/Users/runner/work/1/b/build/tools/tests/test_base.py", line 13, in <module>
2020-10-20T07:01:41.7530760Z 82:     import psutil
2020-10-20T07:01:41.7531950Z 82: ModuleNotFoundError: No module named 'psutil'
2020-10-20T07:01:41.7630710Z 82/83 Test #82: tools_tests_testosqueryi ..............................................***Failed    0.13 sec
```

But the `RELEASE` one is just fine

**Comment by Smjert** [comment]
> The `DEBUG` target still can't find `psutil`:
> 
> ```
> 2020-10-20T07:01:41.1869450Z       Start 81: tools_tests_testosqueryd
> 2020-10-20T07:01:41.1869910Z 
> 2020-10-20T07:01:41.1871780Z 81: Test command: /usr/local/Cellar/cmake/3.18.4/bin/cmake "-E" "env" "PYTHONPATH=/Users/runner/work/1/b/build/python_path" "/usr/local/Frameworks/Python.framework/Versions/3.8/bin/python3.8" "-u" "test_osqueryd.py" "--verbose" "--build" "/Users/runner/work/1/b/build" "--test-configs-dir" "/Users/runner/work/1/b/build/test_configs"
> 2020-10-20T07:01:41.1872960Z 81: Test timeout computed to be: 300
> 2020-10-20T07:01:41.5796140Z 81: Traceback (most recent call last):
> 2020-10-20T07:01:41.5796910Z 81:   File "test_osqueryd.py", line 18, in <module>
> 2020-10-20T07:01:41.5797250Z 81:     import test_base
> 2020-10-20T07:01:41.5797690Z 81:   File "/Users/runner/work/1/b/build/tools/tests/test_base.py", line 13, in <module>
> 2020-10-20T07:01:41.5798160Z 81:     import psutil
> 2020-10-20T07:01:41.5799270Z 81: ModuleNotFoundError: No module named 'psutil'
> 2020-10-20T07:01:41.5900990Z 81/83 Test #81: tools_tests_testosqueryd ..............................................***Failed    0.40 sec
> 2020-10-20T07:01:41.6310960Z test 82
> 2020-10-20T07:01:41.6311440Z       Start 82: tools_tests_testosqueryi
> 2020-10-20T07:01:41.6311750Z 
> 2020-10-20T07:01:41.6313930Z 82: Test command: /usr/local/Cellar/cmake/3.18.4/bin/cmake "-E" "env" "PYTHONPATH=/Users/runner/work/1/b/build/python_path" "/usr/local/Frameworks/Python.framework/Versions/3.8/bin/python3.8" "-u" "test_osqueryi.py" "--verbose" "--build" "/Users/runner/work/1/b/build" "--test-configs-dir" "/Users/runner/work/1/b/build/test_configs"
> 2020-10-20T07:01:41.6315140Z 82: Test timeout computed to be: 300
> 2020-10-20T07:01:41.7528000Z 82: Traceback (most recent call last):
> 2020-10-20T07:01:41.7528980Z 82:   File "test_osqueryi.py", line 17, in <module>
> 2020-10-20T07:01:41.7529780Z 82:     import test_base
> 2020-10-20T07:01:41.7530230Z 82:   File "/Users/runner/work/1/b/build/tools/tests/test_base.py", line 13, in <module>
> 2020-10-20T07:01:41.7530760Z 82:     import psutil
> 2020-10-20T07:01:41.7531950Z 82: ModuleNotFoundError: No module named 'psutil'
> 2020-10-20T07:01:41.7630710Z 82/83 Test #82: tools_tests_testosqueryi ..............................................***Failed    0.13 sec
> ```
> 
> But the `RELEASE` one is just fine

Looking on the CI, it seems that it's bound to a specific version of the image.
There are runs where also the release build errored out in the same manner.

`Current image version: '20201003.1'` these are the ones that do not fail
`Current image version: '20201011.1'` these are the ones that always fail

So there might be something in the env vars or install paths that's misconfigured, which impedes python to find system installed libraries.

> There is no way to ssh into the test runner/instance right?
> 
Not that I know of; I've searched in the past but there's no mention about it or options on the UI I could find.

**Comment by sharvilshah** [comment]
Thanks @Smjert, that's super helpful. It seems we are hitting https://github.com/actions/virtual-environments/issues/1819 and https://github.com/actions/virtual-environments/issues/1818

**Comment by Smjert** [comment]
@sharvilshah I think those two issues have been fixed, there are other test failures now.

About updating the xcode toolchain version, can we also update it in the docs?
Here still mentions version 10.2.1 (which I forgot to update when changing to 10.3): https://github.com/osquery/osquery/blob/master/docs/wiki/development/building.md

Thanks!

**Comment by theopolis** [comment]
Looks like one more fix to table integration tests (or actual table code) is needed: browser_plugins.

**Comment by sharvilshah** [comment]
Okay, taking a look.

**Comment by sharvilshah** [comment]
```
osquery> .mode line
osquery> select * from browser_plugins;
               uid = 0
              name = QuickTime Plug-in 7.7.3
        identifier = com.apple.QuickTime Plugin.plugin
           version = 7.7.3
               sdk = 
       description = The QuickTime Plugin allows you to view a wide variety of multimedia content in web pages. For more information, visit the <A HREF="http://www.apple.com/quicktime">QuickTime</A> Web site.
development_region = en_US
            native = 0
              path = /Library/Internet Plug-Ins/Disabled Plug-Ins/QuickTime Plugin.plugin/
          disabled = 1
osquery> select * from os_version;
         name = Mac OS X
      version = 10.14.6
        major = 10
        minor = 14
        patch = 6
        build = 18G103
     platform = darwin
platform_like = darwin
     codename = 
         arch = x86_64
```

Regarding the failing `browser_plugins` test, this is failing because on macOS 10.14 and prior, there is always a quicktime plug-in that's installed (although disabled). That's what the test expects. 

Starting with macOS 10.15 Catalina, C/NPAPI plugins are deprecated, and QuickTime being one of them is removed. Hence there are no plugins installed on the system by default. 

Is there still any value to having this test? We can of course branch... if running on < 10.15, validate rows, if not assume non exists. Thoughts?

**Comment by theopolis** [comment]
Good find, yeah I think we should branch and test the two distinct expectations.

**Comment by sharvilshah** [comment]
Thanks @theopolis! I think this should be good to go now.

**Comment by terracatta** [comment]
Not derail this, but I want to point out building on Big Sur vs Catalina will impact the `os_version` table. See my failed PR https://github.com/osquery/osquery/pull/6824#issuecomment-748555415. 

I realize it's late in the game to consider using 11.x vs 10.15 but I just wanted to throw this out there in case there isn't much new test breakage building on Big Sur vs Catalina.

**Comment by Smjert** [comment]
> Not to derail this, but I want to point out building on Big Sur vs Catalina will impact the `os_version` table. See my failed PR [#6824 (comment)](https://github.com/osquery/osquery/pull/6824#issuecomment-748555415).
> 
> I realize it's late in the game to consider using 11.x vs 10.15 but I just wanted to throw this out there in case there isn't much new test breakage building on Big Sur vs Catalina.

There's not Big Sur support on Azure Pipelines for now unfortunately.

**Comment by sharvilshah** [comment]
Hey @terracatta, thanks! I am aware about the version differences, but as Stefano mentioned, Big Sur images aren't yet available on Azure Pipelines or Github Actions. 

This just moves the needle from Mojave on the CI.
Whenever Big Sur images are baked and and we adopt them, we can temporarily use `SYSTEM_VERSION_COMPAT=1` to deal with the breakages, if any, until we update our logic to deal with 10.16/11.0 naming.

**Review by theopolis — APPROVED** [review]

**Pull request merged**
