### PR TITLE
CMake: Update the OpenSSL formula

### PR DESCRIPTION
**Pull request by alessandrogario**

### CODE REVIEW

**Comment by theopolis** [comment]
We do not need `nasm` anymore?

**Comment by alessandrogario** [comment]
> We do not need `nasm` anymore?

It was documented in the OpenSSL wiki, but I'm no 100% sure it was ever used

**Comment by theopolis** [comment]
I think you need to update `./wiki/development/building.md` to remove the NASM requirement.

**Comment by alessandrogario** [comment]
> I think you need to update `./wiki/development/building.md` to remove the NASM requirement.

Yeah! I was attempting to get this pass CI first, since macOS kept failing for random Azure reasons :(

**Pull request merged**
