### PR TITLE
site: updating release scripts to reflect new site schema

### PR DESCRIPTION
**Pull request by muffins**
See the [issue on the osquery site repo](https://github.com/osquery/osquery-site/issues/100), the schema for the versions changed

### CODE REVIEW

**Comment by theopolis** [comment]
ok to test

**Comment by muffins** [comment]
ok to test

**Comment by muffins** [comment]
jenkins test windows

**Comment by guliashvili** [comment]
Ok to test

**Comment by muffins** [comment]
jenkins test macos

**Pull request closed without merging**
