### PR TITLE
Use total_size within watchdog on Windows

### PR DESCRIPTION
**Pull request by theopolis**
See #6537, ~~we should at least be using `PrivateBytes` for our definition of `resident_size`.~~

Update: based on discussion here, we are choosing to address the issue by using `total_size` within the watchdog logic.

### CODE REVIEW

**Comment by Smjert** [comment]
Shouldn't we just use the `total_size` column in the watchdog instead (at least for now on Windows)?

`resident_size` is the RSS on Linux which are the active pages in physical memory, so as a concept it sort of maps to the Working Set of Windows.

I believe the issue talks about Windows, but given that Private Bytes also accounts for paged out memory, we should also change the behavior on the other platforms.

On Linux you might need to sum other counters like VmSwap or similar (I only had a brief look at this).

**Comment by Smjert** [comment]
Also, this is slightly tangential, but now that I see, we don't have a "1:1" mapping between Linux and Windows on `total_size` too, because on Linux we use the virtual address space size (VmSize) which is not the same as Windows's Private Bytes, but indeed maps to the Virtual Address space (which also includes shared memory).

I'm not totally sure on Windows how you would take that though.

**Comment by theopolis** [comment]
Right, perhaps we need a new column "private_size". Then we can switch back to using Working Set for Windows. I am unsure how to get the virtual size to accurately set "total_size".

The private size on Linux would be a summation of Private Dirty values within smaps. (My best guess at the most accurate representation.)

**Comment by Smjert** [comment]
> Right, perhaps we need a new column "private_size". Then we can switch back to using Working Set for Windows. I am unsure how to get the virtual size to accurately set "total_size".
> 

I'm in favor of adding such a column, but what I was trying to say is that the expectation and definition of `resident_size` is the memory that is kept in physical memory, so setting it to the value of Private Bytes would be incorrect, because it also contains paged out memory.

Also given that we already have such value in the `total_size` column, wouldn't it be better, for this specific watchdog fix, to actually change the watchdog so that it looks at `total_size` instead of `resident_size`, on Windows?

**Comment by theopolis** [comment]
Yeap, I agree

**Comment by theopolis** [comment]
Introducing a new `private_size` column is a bit complex at this point in time. Let's go with the half-measure band aid and update the watcher logic for now.

**Review by directionless — APPROVED** [review]

**Pull request merged**
