### PR TITLE
CMake: Workaround Thrift symlink issue on Windows

### PR DESCRIPTION
**Pull request by Smjert**
CMake doesn't support reading and therefore copying Windows symlinks.
A recent update to Thrift creates a symlink in its tutorial folder,
which makes the copy after patch process fail.
As a workaround we remove the tutorial folder,
since we don't care about it anyway.

### CODE REVIEW

**Comment by theopolis** [comment]
Instead of a patch file, could we add CMake logic to remove the folder?

**Comment by Smjert** [comment]
> Instead of a patch file, could we add CMake logic to remove the folder?

Ok, also this fails on the CI because it's using the "wrong" git, which when cloning it disables support for symlinks and therefore creates a normal text file with the path of the target written in it.
This is another fix I have to do (selecting the correct git version), in a different PR.

**Comment by theopolis** [comment]
Should master also fail CI due to the symlink/git-detection issue?

**Comment by Smjert** [comment]
> Should master also fail CI due to the symlink/git-detection issue?

It should be failing already yes, though it seems that due to the version selected (which is not the one installed in C:\Program Files), that defaults to `core.symlinks false`, which disables support to symlinks and proceeds substituting them with text files containing the target path.
Which is why it doesn't actually fail now.

**Comment by Smjert** [comment]
I ended up skipping the folder, because deleting it would make the other patch fail (because `git apply` also checks the index the patch was created against).

**Pull request merged**
