### PR TITLE
Report session id in processes table for linux

### LINKED ISSUE #4103: tables: report also session id in processes table under linux
It would be nice to have session id also included in the process table for linux.
In _/proc/PID/stat_ session id is the 6th value. 

While in recent kernels /proc/PID/status also tells us the session id in the _NSsid_ line, this is missing in older (but still used) kernels.

### PR DESCRIPTION
**Pull request by micheal-o**
Fixes #4103

### CODE REVIEW

**Comment by muffins** [comment]
ok to test

**Comment by muffins** [comment]
@micheal-o can you address @fmanco's note, and also rebase this PR on top of the master branch?

**Comment by Smjert** [comment]
Hi @micheal-o, thanks for your contribution!
Any time/interest to address @muffins note?

**Comment by theopolis** [comment]
Thanks again for your contribution and pull request! Heads up, we are going to close older PRs to help with project organization and focus. If you are still eager to land your changes please feel welcomed to re-open the request. If you feel like you were waiting for answers or a review from other project contributors please mention me and I'll take a look as soon as possible.

For this PR specifically I would ask that we ask more details about the original request, for example, how this new data is useful for folks. And since this targets a "popular" or "common" table, we should consider if the data is generalized to other platforms first.

**Pull request closed without merging**
