### PR TITLE
Rename `kIOMasterPortDefault` to `kIOMainPortDefault`

### PR DESCRIPTION
**Pull request by directionless**
Testing something locally, I noticed I was getting deprecated warnings. It looks like apple renamed this.

### CODE REVIEW

**Review by sharvilshah — COMMENTED** [review]
Do we know if this has been back-ported to older versions of macOS? IIRC we still use macOS 10.12 as min SDK version

**Comment by directionless** [comment]
> Do we know if this has been back-ported to older versions of macOS? IIRC we still use macOS 10.12 as min SDK version

My plan was to see if CI succeeded, and if so, test. Sadly, CI did not succeed.

**Comment by sharvilshah** [comment]
Just checked, this does require SDK to be macOS 12 Monterey. A bit messy, but we can `ifdef` it..?

**Comment by directionless** [comment]
I don't think it solves a problem. Probably better to just defer it until we have to do something

**Pull request closed without merging**
