### PR TITLE
return correct value here

### PR DESCRIPTION
**Pull request by pawel-lmcb**
Make sure we return a bool here

### CODE REVIEW

**Comment by theopolis** [comment]
What bug are we trying to fix here?

**Comment by alessandrogario** [comment]
Hello @pawel-lmcb!

Thanks for the fix :smile:!

Since we are using `-Wall`, I was expecting we would also get `-Wreturn-type` - and at least get a warning for this issue.

Can you update the flags to include `-Wreturn-type` and `-Werror=return-type` if that's not the case?

In the future we should probably move to the full `-Werror`

**Comment by pawel-lmcb** [comment]
@theopolis the return statements do not explicitly return a bool. This is what I was attempting to fix, as when iterating on this file in windows, we ran into compilation issues that the method did not return a bool.

Also, I did sign the CLA (and it was emailed to me) not sure if I need to do something else to get that signed off?

**Comment by Smjert** [comment]
> @theopolis the return statements do not explicitly return a bool. This is what I was attempting to fix, as when iterating on this file in windows, we ran into compilation issues that the method did not return a bool.

That's very strange though, that return is correct as it is since it's inside a lambda that's called by `std::call_once`, so the return want cause to return from `isEc2Instance()`.
All the other paths correctly returns a boolean.

**Comment by pawel-lmcb** [comment]
@Smjert so the logic to call this once is incorrect. Let me explain.https://github.com/osquery/osquery/issues/5817 When we boot up in Windows 2008 R2 or Windows 2012, and install OSQuery as a service, the local hypervisor endpoint that this plugin his isn't available. It takes some time for this to become fully available. We haven't experienced the same issue on later versions of Windows (2016 or later).

the std::call_once will result in incorrect behaviour. Maybe it makes sense for this to be a larger discussion/different issue then? Open to suggestions here.

**Comment by Smjert** [comment]
> @Smjert so the logic to call this once is incorrect. Let me explain.#5817 When we boot up in Windows 2008 R2 or Windows 2012, and install OSQuery as a service, the local hypervisor endpoint that this plugin his isn't available. It takes some time for this to become fully available. We haven't experienced the same issue on later versions of Windows (2016 or later).
> 
> the std::call_once will result in incorrect behaviour. Maybe it makes sense for this to be a larger discussion/different issue then? Open to suggestions here.

I would definitely open an issue to discuss your specific issue and also get a more complete resolution.

**Comment by theopolis** [comment]
I'm going to close this out, let's move discussion to the issue.

**Pull request closed without merging**
