### PR TITLE
Correct the section where the users and groups service flags are described

### PR DESCRIPTION
**Pull request by Smjert**
Related to https://github.com/osquery/osquery/pull/7516

### CODE REVIEW

**Comment by mike-myers-tob** [comment]
This just moves some of the wiki text under a different heading, is that right?

**Comment by Smjert** [comment]
> This just moves some of the wiki text under a different heading, is that right?

Yes! I messed up the location.

**Comment by Smjert** [comment]
I've now also slightly updated the start of the description, to remove the redundant "Windows only flag...", and also fix one of the numeric values that was incorrectly including also the `ms` suffix.

**Comment by mike-myers-tob** [comment]
LGTM

**Review by directionless — APPROVED** [review]

**Pull request merged**
