### PR TITLE
add a timeout to curl_certificate implementation

### PR DESCRIPTION
**Pull request by nabilschear**
to Fix https://github.com/osquery/osquery/issues/6615 i've updated curl_certificates to have a timeout so it doesn't hang forever.  It works by setting up the socket , setting a recv timeout, connecting, and then passing it into BIO to complete the TLS handshake.  

I've tested this on Mac, Windows, and Linux and should provide feature parity with the old BIO-based implementation (supports ipv6 and ipv4). 

@theopolis  I know you worked on this code a few years ago, so it might be something you can help review.

I welcome your suggestions!

### CODE REVIEW

**Comment by theopolis** [comment]
Thanks for the PR, a few things:

First, do you mind squashing your commits into a single commit and then resetting the author to be your github username or `USERNAME@users.noreply.github.com`? This will help with the CLA tracking.

Second, I think we should include the fix for all OSes and avoid an `ifdef`. Is there a way we can use boost's ASIO or another abstraction layer to help us?

**Comment by nabilschear** [comment]
@theopolis I got a windows vm and tested out the behavior on windows.  Like Linux/Mac, it also hangs indefinitely.  I'm not sure how much asio will help unless we completely re-write the cert implementation.  To use the openssl calls, we need a socket.

**Comment by nabilschear** [comment]
hi @theopolis , so i got myself a windows vm and updated the socket code to work with this change.  w00t!  But now I'm getting stuck by the win32 build process for the PR.  It seems to be failing somewhere deep in a kafka library (no where the changes I've made).  This builds and runs just fine for me on my windows box.  Is this a known issue with windows builds?  Is there someone who can help me look through the logs to see why it's failing?

**Comment by nabilschear** [comment]
hrm, I'm stuck here.  I checked out this branch to a clean win 10 environment, followed these instructions: https://osquery.readthedocs.io/en/stable/development/building/ for windows.  

```
cmake -G "Visual Studio 16 2019" -A x64 -T v141 ..
 cmake --build . --config Release --target package
```

I'm not getting any errors related to libdrkafka: 
```
FAILED: libs/src/librdkafka/CMakeFiles/thirdparty_librdkafka_c.dir/src/src/tinycthread.c.obj 
sccache.exe C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe  /nologo -DLIBRDKAFKA_GIT_VERSION=\"v1.0.1\" -DLIBRDKAFKA_STATICLIB -DNDEBUG -DNTDDI_VERSION=NTDDI_WIN7 -DWITH_HDRHISTOGRAM -DWITH_PLUGINS -DWITH_SASL_SCRAM -DWITH_SSL -DWITH_ZLIB -DWITH_ZSTD -DWITH_ZSTD_STATIC -DXXH_NAMESPACE=rdkafka_ -DXXH_PRIVATE_API -D_WIN32_WINNT=_WIN32_WINNT_WIN7 -Ilibs\src\librdkafka\include\librdkafka -ID:\a\1\s\libraries\cmake\source\librdkafka\src\src -Iinstalled_formulas\openssl\include -ID:\a\1\s\libraries\cmake\source\zlib\src -ID:\a\1\s\libraries\cmake\source\zstd\src\lib -ID:\a\1\s\libraries\cmake\source\zstd\src\lib\common /DWIN32 /D_WINDOWS  /MT /O2 /Ob2 /DNDEBUG /Ot /guard:cf /bigobj /W0 -std:c11 /showIncludes /Folibs\src\librdkafka\CMakeFiles\thirdparty_librdkafka_c.dir\src\src\tinycthread.c.obj /Fdlibs\src\librdkafka\CMakeFiles\thirdparty_librdkafka_c.dir\thirdparty_librdkafka_c.pdb /FS -c D:\a\1\s\libraries\cmake\source\librdkafka\src\src\tinycthread.c
D:\a\1\s\libraries\cmake\source\librdkafka\src\src\tinycthread.c(482): error C2054: expected '(' to follow '_Thread_local'
```

**Comment by nabilschear** [comment]
trying another useless commit to kick off the build again to see if it was a transient issue.

**Comment by nabilschear** [comment]
and it was a transient issue.  I think I'll make the timeout a query parameter and extend the default.

**Comment by nabilschear** [comment]
i'll close this until it's ready for review

**Comment by theopolis** [comment]
Hey, I’m available to review the code now. What’s the next step here?

**Pull request closed without merging**
