### PR TITLE
Adding Hidden LaunchAgent/Daemon Discovery

### PR DESCRIPTION
**Pull request by calhall**
# Hidden LaunchAgent/Daemon Discovery

## Background

As per this issue -> https://github.com/osquery/osquery/issues/7703 <- this PR introduces the capability for osquery to identify LaunchAgents/Daemons that are defined in hidden `.plist` files.

The TL;DR from the issue linked above is -> 

Malware commonly persists on macOS devices using LaunchAgents/Daemons. It [has been observed](https://www.welivesecurity.com/2022/07/19/i-see-what-you-did-there-look-cloudmensis-macos-spyware/) that certain malware samples have been utilising hidden `plist` files i.e. `/Library/LaunchDaemons/.com.apple.WindowServer.plist`. This PR aims to cover off this blind spot within the current launchd table.

## Changes
 Three files have been altered within this PR:
 * `osquery/filesystem/filesystem.cpp` - adding capability to maintain hidden file wildcards to the `replaceGlobWildcards` function & adds `listHiddenFilesInDirectory` function
 * `osquery/filesystem/filesystem.h` - adds basic structure for `listHiddenFilesInDirectory` function
 * `osquery/tables/system/darwin/launchd.cpp` - utilises new `listHiddenFilesInDirectory` with existing LaunchAgent/Daemon paths
 
 ## Impact

This PR prevents malicious LaunchAgents/Daemons from evading detection by using a hidden plist files. As shown in the screenshot below, we can now identify these hidden plists:
<br>
image

### CODE REVIEW

**Comment by mike-myers-tob** [comment]
Looks like the filesystem.cpp changes broke tests on Windows and Linux, do you think this can be fixed?

**Comment by calhall** [comment]
> Looks like the filesystem.cpp changes broke tests on Windows and Linux, do you think this can be fixed?

I imagine so! I just need to find the time to understand what the tests are doing... as I'm not 100% certain as to why these changes would have affected any existing tests.

**Comment by directionless** [comment]
As I understand it, one of the effects of https://github.com/osquery/osquery/pull/7974 is that hidden files are enumerated with `listDirectoriesInDirectory`. Does that change the approach here?

**Comment by Smjert** [comment]
@calhall the changes on this commit https://github.com/osquery/osquery/pull/7704/commits/5e31b14d05b8c3a62b5fc36d908dc654eb73a5c5 should not exist, because they are reverting some changes happened on `master`.

When rebasing on top of master (with `git rebase -i master`) you should be only seeing your new commits and nothing from master itself.

It seems to me that you could entirely drop https://github.com/osquery/osquery/pull/7704/commits/5e31b14d05b8c3a62b5fc36d908dc654eb73a5c5 and maybe attempt a rebase again if your branch commits are not on top of master?

**Comment by calhall** [comment]
> 

Yeah I've got some got unusual behaviour going on after my initial rebase 🤔 I'll clean that up. Should be a super simple one file change at this point!

**Comment by calhall** [comment]
I've opened up a clean PR as you can see above to track this work. Conflicts were making this messier than it needed to be 😆

**Comment by Smjert** [comment]
@calhall  A bit late on commenting but, for the next time it's not necessary to open a new PR.
Since I assume you locally re-created the branch, you could've made a backup of the original one connected with this PR (`git checkout -b "<your branch name>-backup"`, while being checked out with the original branch), then you can delete the original and recreate it with the same name and the fix to it you need.

Finally you force push the branch, which will update the PR with the correct commits.

Last suggestion (more for organization) is to never use `master` as the name of the branch for a PR.

**Pull request closed without merging**
