### PR TITLE
Simplify how third party libraries formula work

### PR DESCRIPTION
**Pull request by Smjert**
Remove a level of indirection when configuring and building formulas.
This should simplify working with them and also remove some issues
encountered when trying to build on Windows.

This should address: https://github.com/osquery/osquery/issues/6287

Depends on: https://github.com/osquery/osquery/pull/6302

### CODE REVIEW

**Comment by Smjert** [comment]
Retrigger CI.

**Comment by directionless** [comment]
You asked if people could build this branch. Working off commit f0fa6aa710cf96dd5d0f528fbb94aaceb9d8f514, I had no trouble building. I did see a couple test failures:
```
git checkout remotes/trailofbits/stefano/build/simplify-formula
mkdir build-simplify
cd build-simplify/
cmake -DOSQUERY_BUILD_TESTS=ON ../
make -j8
./osquery/osqueryi
cmake --build . --target test

98% tests passed, 2 tests failed out of 80

Total Test time (real) =  77.69 sec

The following tests FAILED:
	 79 - tools_tests_testosqueryd (Failed)
	 80 - tests_integration_tables-test (Failed)
```

**Comment by Smjert** [comment]
> You asked if people could build this branch. Working off commit [f0fa6aa](https://github.com/osquery/osquery/commit/f0fa6aa710cf96dd5d0f528fbb94aaceb9d8f514), I had no trouble building. I did see a couple test failures:
> 
> ```
> git checkout remotes/trailofbits/stefano/build/simplify-formula
> mkdir build-simplify
> cd build-simplify/
> cmake -DOSQUERY_BUILD_TESTS=ON ../
> make -j8
> ./osquery/osqueryi
> cmake --build . --target test
> 
> 98% tests passed, 2 tests failed out of 80
> 
> Total Test time (real) =  77.69 sec
> 
> The following tests FAILED:
> 	 79 - tools_tests_testosqueryd (Failed)
> 	 80 - tests_integration_tables-test (Failed)
> ```

Thanks!
Yeah those test failures are most likely unrelated and happening right now when run in local machines vs CI.
I have to open other issues for them.

**Comment by theopolis** [comment]
Running `make` out of my already-configured build directory:
```
CMake Error at libraries/cmake/source/librpm/CMakeLists.txt:114 (add_library):
  Cannot find source file:

    /home/teddy/git/osquery-prod/libraries/cmake/source/librpm/src/lib/backend/dummydb.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  libraries/cmake/source/librpm/CMakeLists.txt:161 (librpmMain)


CMake Error at libraries/cmake/source/librpm/CMakeLists.txt:114 (add_library):
  No SOURCES given to target: thirdparty_librpm
Call Stack (most recent call first):
  libraries/cmake/source/librpm/CMakeLists.txt:161 (librpmMain)


CMake Generate step failed.  Build files cannot be regenerated correctly.
Makefile:12104: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
```

Fixed with:
```
git submodule update --init 
```

Then everything works fine :)

**Comment by Smjert** [comment]
> Running `make` out of my already-configured build directory:
> 
> ```
> CMake Error at libraries/cmake/source/librpm/CMakeLists.txt:114 (add_library):
>   Cannot find source file:
> 
>     /home/teddy/git/osquery-prod/libraries/cmake/source/librpm/src/lib/backend/dummydb.c
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
>   .hpp .hxx .in .txx
> Call Stack (most recent call first):
>   libraries/cmake/source/librpm/CMakeLists.txt:161 (librpmMain)
> 
> 
> CMake Error at libraries/cmake/source/librpm/CMakeLists.txt:114 (add_library):
>   No SOURCES given to target: thirdparty_librpm
> Call Stack (most recent call first):
>   libraries/cmake/source/librpm/CMakeLists.txt:161 (librpmMain)
> 
> 
> CMake Generate step failed.  Build files cannot be regenerated correctly.
> Makefile:12104: recipe for target 'cmake_check_build_system' failed
> make: *** [cmake_check_build_system] Error 1
> ```
> 
> Fixed with:
> 
> ```
> git submodule update --init 
> ```
> 
> Then everything works fine :)

Ah yes, that is to be expected and it's actually due to the update of openssl.
Maybe I can add a line in the commit description to either start from scratch or remember to run that command.

**Comment by Smjert** [comment]
Rebased on latest master, since the PR it depends on landed.

**Comment by theopolis** [comment]
@Smjert ready to merge?

**Comment by Smjert** [comment]
> @Smjert ready to merge?

Yeah I was waiting confirmation from this issue https://github.com/osquery/osquery/issues/6287, since everything looks good I'll merge it now, thanks!

**Pull request merged**
