### PR TITLE
build: Add Azure tables to specs CMakeLists

### LINKED ISSUE #6501: Azure tables are missing
# Bug report

### What operating system and version are you using?

Seen on different platforms

### What version of osquery are you using?

4.3.0

### What steps did you take to reproduce the issue?

Attempting to query azure_instance_metadata or azure_instance_tags

### What did you expect to see?

I expected for the tables to be available as per: https://osquery.io/schema/4.3.0/#azure_instance_metadata

### What did you see instead?
 
I saw table not found errors.
image

### PR DESCRIPTION
**Pull request by theopolis**
Fixes #6501.

### CODE REVIEW

**Comment by Smjert** [comment]
@theopolis looks good although I'm not sure why some Windows tests started crashing like that.
I'm trying to investigate.

**Comment by Smjert** [comment]
This is a call stack taken with a RelWithDebInfo build + AppVerif that shows, in the case of the osquery_distributed_tests-test, where it's crashing:
```
[Inline Frame] osquery_distributed_tests-test.exe!boost::asio::detail::timer_queue<boost::asio::detail::forwarding_posix_time_traits>::per_timer_data::{ctor}() Line 52
	at c:\osquery\src\libraries\cmake\source\boost\src\libs\asio\include\boost\asio\detail\timer_queue.hpp(52)
[Inline Frame] osquery_distributed_tests-test.exe!boost::asio::detail::io_object_impl<boost::asio::detail::deadline_timer_service<boost::asio::time_traits<boost::posix_time::ptime>>,boost::asio::executor>::{ctor}(boost::asio::io_context &) Line 89
	at c:\osquery\src\libraries\cmake\source\boost\src\libs\asio\include\boost\asio\detail\io_object_impl.hpp(89)
[Inline Frame] osquery_distributed_tests-test.exe!boost::asio::basic_deadline_timer<boost::posix_time::ptime,boost::asio::time_traits<boost::posix_time::ptime>,boost::asio::executor>::{ctor}(boost::asio::io_context & context, void *) Line 174
	at c:\osquery\src\libraries\cmake\source\boost\src\libs\asio\include\boost\asio\basic_deadline_timer.hpp(174)
osquery_distributed_tests-test.exe!osquery::http::Client::Client(const osquery::http::Client::Options & opts) Line 207
	at c:\osquery\build\ninja\ns_osquery_remote_httpclient\osquery\remote\http_client.h(207)
[Inline Frame] osquery_distributed_tests-test.exe!std::_Ref_count_obj<osquery::http::Client>::{ctor}() Line 1801
	at c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.16.27023\include\memory(1801)
osquery_distributed_tests-test.exe!std::make_shared<osquery::http::Client>() Line 1866
	at c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.16.27023\include\memory(1866)
osquery_distributed_tests-test.exe!osquery::getClient() Line 188
	at c:\osquery\src\osquery\remote\transports\tls.cpp(188)
osquery_distributed_tests-test.exe!osquery::TLSTransport::sendRequest(const std::string & params, bool compress) Line 260
	at c:\osquery\src\osquery\remote\transports\tls.cpp(260)
osquery_distributed_tests-test.exe!osquery::Request<osquery::TLSTransport,osquery::JSONSerializer>::call(const osquery::JSON & params) Line 239
	at c:\osquery\build\ninja\ns_osquery_remote_requests\osquery\remote\requests.h(239)
osquery_distributed_tests-test.exe!osquery::TLSEnrollPlugin::requestKey(const std::string & uri, std::string & node_key) Line 100
	at c:\osquery\src\plugins\remote\enroll\tls_enroll.cpp(100)
osquery_distributed_tests-test.exe!osquery::TLSEnrollPlugin::enroll() Line 71
	at c:\osquery\src\plugins\remote\enroll\tls_enroll.cpp(71)
osquery_distributed_tests-test.exe!osquery::EnrollPlugin::call(const std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>> & request, std::vector<std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>>,std::allocator<std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>>>> & response) Line 135
	at c:\osquery\src\osquery\remote\enroll\enroll.cpp(135)
osquery_distributed_tests-test.exe!osquery::RegistryInterface::call(const std::string & item_name, const std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>> & request, std::vector<std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>>,std::allocator<std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>>>> & response) Line 144
	at c:\osquery\src\osquery\registry\registry_interface.cpp(144)
osquery_distributed_tests-test.exe!osquery::RegistryFactory::call(const std::string & registry_name, const std::string & item_name, const std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>> & request, std::vector<std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>>,std::allocator<std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>>>> & response) Line 176
	at c:\osquery\src\osquery\registry\registry_factory.cpp(176)
osquery_distributed_tests-test.exe!osquery::getNodeKey(const std::string & enroll_plugin) Line 83
	at c:\osquery\src\osquery\remote\enroll\enroll.cpp(83)
osquery_distributed_tests-test.exe!osquery::TLSRequestHelper::makeURI(const std::string & endpoint) Line 49
	at c:\osquery\build\ninja\ns_osquery_remote_utility\osquery\remote\utility.h(49)
osquery_distributed_tests-test.exe!osquery::TLSDistributedPlugin::setUp() Line 61
	at c:\osquery\src\plugins\distributed\tls_distributed.cpp(61)
osquery_distributed_tests-test.exe!osquery::RegistryInterface::setActive(const std::string & item_name) Line 88
	at c:\osquery\src\osquery\registry\registry_interface.cpp(88)
osquery_distributed_tests-test.exe!osquery::RegistryFactory::setActive(const std::string & registry_name, const std::string & item_name) Line 218
	at c:\osquery\src\osquery\registry\registry_factory.cpp(218)
osquery_distributed_tests-test.exe!osquery::DistributedTests::startServer() Line 70
	at c:\osquery\src\osquery\distributed\tests\distributed_tests.cpp(70)
osquery_distributed_tests-test.exe!osquery::DistributedTests_test_workflow_Test::TestBody() Line 194
	at c:\osquery\src\osquery\distributed\tests\distributed_tests.cpp(194)
osquery_distributed_tests-test.exe!testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test,void>(testing::Test * object, void(testing::Test::*)() method, const char * location) Line 2428
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest.cc(2428)
osquery_distributed_tests-test.exe!testing::internal::HandleExceptionsInMethodIfSupported<testing::Test,void>(testing::Test * object, void(testing::Test::*)() method, const char * location) Line 2479
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest.cc(2479)
osquery_distributed_tests-test.exe!testing::Test::Run() Line 2524
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest.cc(2524)
osquery_distributed_tests-test.exe!testing::TestInfo::Run() Line 2697
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest.cc(2697)
osquery_distributed_tests-test.exe!testing::TestCase::Run() Line 2811
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest.cc(2811)
osquery_distributed_tests-test.exe!testing::internal::UnitTestImpl::RunAllTests() Line 5176
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest.cc(5176)
osquery_distributed_tests-test.exe!testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl,bool>(testing::internal::UnitTestImpl * object, bool(testing::internal::UnitTestImpl::*)() method, const char * location) Line 2428
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest.cc(2428)
osquery_distributed_tests-test.exe!testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl,bool>(testing::internal::UnitTestImpl * object, bool(testing::internal::UnitTestImpl::*)() method, const char * location) Line 2479
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest.cc(2479)
osquery_distributed_tests-test.exe!testing::UnitTest::Run() Line 4786
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest.cc(4786)
[Inline Frame] osquery_distributed_tests-test.exe!RUN_ALL_TESTS() Line 2341
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\include\gtest\gtest.h(2341)
osquery_distributed_tests-test.exe!main(int argc, char * * argv) Line 37
	at c:\osquery\build\ninja\libs\src\patched-source\googletest\src\googletest\src\gtest_main.cc(37)
```

The http::Client constructor is:
https://github.com/osquery/osquery/blob/d6e7b257069609d4efdad959edeb881ae13dd95f/osquery/remote/http_client.h#L205-L217

At line 207 there's the member initialization and the call stack shows that the issue is with a deadline_timer, which is `timer_` in http::Client.

http::Client members:
https://github.com/osquery/osquery/blob/d6e7b257069609d4efdad959edeb881ae13dd95f/osquery/remote/http_client.h#L328-L336

The last frame, where the access violation happens is the boost::asio::detail::timer_queue<[...]>::per_timer_data constructor, which is:
```
  class per_timer_data
  {
  public:
    per_timer_data() :
      heap_index_((std::numeric_limits<std::size_t>::max)()),
      next_(0), prev_(0) <--- The access violation is here
    {
    }
```

The http::Client class is instanced here:
https://github.com/osquery/osquery/blob/master/osquery/remote/transports/tls.cpp#L180-L202

Trying to move the ClientOptions member variable just after the deadline_timer position in the http::Client class, make the access violation move to one of the first members initialized in the ClientOptions class.

Completely removing any code in the getClient function, tls.cpp, and just doing a `new http::Client()` still gets the access violation.

Reproducing the initialization of the deadline_timer via io_context outside of the http::Client class and in the getClient function, do not trigger an access violation.

The order of initialization of ioc_ in respect to the other members that take it as a costructor argument should not be an issue, because it should happen in the order it has been declared in the class member list.

There must be something trivial (or not?) that's happening here that it currently escapes me..

**Comment by theopolis** [comment]
This is curious, I wonder if @Breakwell can help us out?

**Comment by Breakwell** [comment]
> This is curious, I wonder if @Breakwell can help us out?

So I have taken a look and you'll notice in the aws util the http_client header is included first: https://github.com/osquery/osquery/blob/master/osquery/utils/aws/aws_util.cpp#L12 however this isn't done in the azure util: https://github.com/osquery/osquery/blob/master/osquery/utils/azure/azure_util.cpp#L15 I have included the header first and this seems to have solved the problem.

**Comment by Smjert** [comment]
> > This is curious, I wonder if @Breakwell can help us out?
> 
> So I have taken a look and you'll notice in the aws util the http_client header is included first: https://github.com/osquery/osquery/blob/master/osquery/utils/aws/aws_util.cpp#L12 however this isn't done in the azure util: https://github.com/osquery/osquery/blob/master/osquery/utils/azure/azure_util.cpp#L15 I have included the header first and this seems to have solved the problem.

Wow thanks!
I did saw that but decided that since it wasn't a build problem, that should not have been the cause.
I forgot the pleasure of incorrect includes on Windows.

**Pull request merged**
