### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by myersg86**
```
CHANGELOG.md: Plaforms -> Platforms, occures -> occurs
docs/wiki/deployment/configuration.md: specificied -> specified
osquery/experimental/README.md:5: it wether -> whether it
```

To submit a PR please make sure to follow the next steps:

- [ ] Read the `CONTRIBUTING.md` guide at the root of the repo.
- [ ] Ensure the code is formatted building the `format_check` target.  
      If it is not, then move the committed files to the git staging area,
      build the `format` target to format them, and then re-commit.
      [More information is available on the wiki](https://osquery.readthedocs.io/en/latest/development/building/#formatting-the-code).
- [ ] Ensure your PR contains a single logical change.
- [ ] Ensure your PR contains tests for the changes you're submitting.
- [ ] Describe your changes with as much detail as you can.
- [ ] Link any issues this PR is related to.
- [ ] Remove the text above.

### CODE REVIEW

**Review by directionless — COMMENTED** [review]
Hi @myersg86 ! thank you so much for your contribution. The fixes look fine, though we do require the CLA. Are you having any issues with it?

**Comment by myersg86** [comment]
Thanks @directionless ! I've signed and submitted my CLA.

**Comment by directionless** [comment]
The CLA shows as unsigned. I suspect this is because some of the git commits list a different author than your @myersg86 account. (specifically, they're from `gitlab-mirror-video`) You should be able to re-write the commits from whatever your email address should be

**Comment by myersg86** [comment]
@directionless thanks for the pointer, I didn't realize that there was a commit author mismatch - how embarassing. :sweat_smile: 
Should be good now! :bow:

**Review by directionless — APPROVED** [review]

**Pull request merged**
