### PR TITLE
tests: Reduce flakiness of test_osqueryi

### PR DESCRIPTION
**Pull request by theopolis**
This PR aims to reduce the flakiness of `test_osqueryi` by reducing the complexity of flag usage. It also adds the 'default flags' to `TimeoutRunner`, preventing local state from impacting the tests.

### CODE REVIEW

**Comment by theopolis** [comment]
This attempts to address https://github.com/osquery/osquery/issues/6667 and https://github.com/osquery/osquery/issues/6668.

**Comment by Smjert** [comment]
Thanks for looking into this!

I had a quick look but the part that doesn't convince me is adding more `@test_base.flaky` decorators.
I would just remove those decorators, those tests should be deterministic, and while originally attempting to restore these python tests, my experience is that the flaky decorator has hidden issues several times.

**Comment by theopolis** [comment]
I agree, can do. I am pretty optimistic about the other changes in this PR. I will update and remove the decorators momentarily.

**Comment by theopolis** [comment]
(just running the tests again)

**Review by directionless — APPROVED** [review]
Seems reasonable

**Pull request merged**
