### PR TITLE
tests: Enable RocksDB plugin tests

### PR DESCRIPTION
**Pull request by theopolis**
Not sure why this was disabled. If it was enabled we would have had less breakage in 4.0.1.

### CODE REVIEW

**Comment by Smjert** [comment]
This is disabled in BUCK too.

**Comment by theopolis** [comment]
The failure here is:
```
test 81
      Start 81: plugins_database_tests_rocksdbtests-test

81: Test command: /__w/1/b/build/plugins/database/tests/plugins_database_tests_rocksdbtests-test
81: Test timeout computed to be: 10000000
81: Running main() from /__w/1/s/libraries/cmake/source/googletest/src/googletest/src/gtest_main.cc
81: [==========] Running 20 tests from 2 test cases.
81: [----------] Global test environment set-up.
81: [----------] 11 tests from RocksDBDatabasePluginTests
81: [ RUN      ] RocksDBDatabasePluginTests.test_plugin_check
81: [       OK ] RocksDBDatabasePluginTests.test_plugin_check (664 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_reset
81: [       OK ] RocksDBDatabasePluginTests.test_reset (281 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_put
81: [       OK ] RocksDBDatabasePluginTests.test_put (240 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_putBatch
81: [       OK ] RocksDBDatabasePluginTests.test_putBatch (231 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_get
81: [       OK ] RocksDBDatabasePluginTests.test_get (226 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_delete
81: [       OK ] RocksDBDatabasePluginTests.test_delete (168 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_delete_range
81: [       OK ] RocksDBDatabasePluginTests.test_delete_range (236 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_scan
81: [       OK ] RocksDBDatabasePluginTests.test_scan (172 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_scan_limit
81: [       OK ] RocksDBDatabasePluginTests.test_scan_limit (170 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_rocksdb_loglevel
81: [       OK ] RocksDBDatabasePluginTests.test_rocksdb_loglevel (157 ms)
81: [ RUN      ] RocksDBDatabasePluginTests.test_corruption
81: /__w/1/s/plugins/database/tests/rocksdb.cpp:37: Failure
81: Value of: pathExists(path_)
81:   Actual: false
81: Expected: true
81: [  FAILED  ] RocksDBDatabasePluginTests.test_corruption (154 ms)
81: [----------] 11 tests from RocksDBDatabasePluginTests (2699 ms total)
81: 
81: [----------] 9 tests from EphemeralDatabasePluginTests
81: [ RUN      ] EphemeralDatabasePluginTests.test_plugin_check
81: [       OK ] EphemeralDatabasePluginTests.test_plugin_check (0 ms)
81: [ RUN      ] EphemeralDatabasePluginTests.test_reset
81: [       OK ] EphemeralDatabasePluginTests.test_reset (0 ms)
81: [ RUN      ] EphemeralDatabasePluginTests.test_put
81: [       OK ] EphemeralDatabasePluginTests.test_put (0 ms)
81: [ RUN      ] EphemeralDatabasePluginTests.test_putBatch
81: [       OK ] EphemeralDatabasePluginTests.test_putBatch (0 ms)
81: [ RUN      ] EphemeralDatabasePluginTests.test_get
81: [       OK ] EphemeralDatabasePluginTests.test_get (1 ms)
81: [ RUN      ] EphemeralDatabasePluginTests.test_delete
81: [       OK ] EphemeralDatabasePluginTests.test_delete (0 ms)
81: [ RUN      ] EphemeralDatabasePluginTests.test_delete_range
81: [       OK ] EphemeralDatabasePluginTests.test_delete_range (0 ms)
81: [ RUN      ] EphemeralDatabasePluginTests.test_scan
81: [       OK ] EphemeralDatabasePluginTests.test_scan (0 ms)
81: [ RUN      ] EphemeralDatabasePluginTests.test_scan_limit
81: [       OK ] EphemeralDatabasePluginTests.test_scan_limit (0 ms)
81: [----------] 9 tests from EphemeralDatabasePluginTests (1 ms total)
81: 
81: [----------] Global test environment tear-down
81: [==========] 20 tests from 2 test cases ran. (2700 ms total)
81: [  PASSED  ] 19 tests.
81: [  FAILED  ] 1 test, listed below:
81: [  FAILED  ] RocksDBDatabasePluginTests.test_corruption
```

**Comment by theopolis** [comment]
Interesting, looks like `clang-format` is not installed (Linux):
```
[command]/usr/local/bin/cmake --build . --target format_check
Scanning dependencies of target format_check
Failed to run formatting script


error: cannot find executable "clang-format"

CMakeFiles/format_check.dir/build.make:57: recipe for target 'CMakeFiles/format_check' failed
make[3]: *** [CMakeFiles/format_check] Error 1
CMakeFiles/Makefile2:198: recipe for target 'CMakeFiles/format_check.dir/all' failed
make[2]: *** [CMakeFiles/format_check.dir/all] Error 2
CMakeFiles/Makefile2:205: recipe for target 'CMakeFiles/format_check.dir/rule' failed
make[1]: *** [CMakeFiles/format_check.dir/rule] Error 2
Makefile:210: recipe for target 'format_check' failed
make: *** [format_check] Error 2
```

**Comment by theopolis** [comment]
@smjert, what do you think of my Azure edits? Would you like to handle that differently in a separate PR?

**Comment by Smjert** [comment]
> @Smjert, what do you think of my Azure edits? Would you like to handle that differently in a separate PR?

I would prefer having that PATH set, if using the custom toolchain, inside CMake when it calls the script, so that's the same also for developers that use that target to format the code
I'll open a PR.

**Comment by Smjert** [comment]
Here it is: https://github.com/osquery/osquery/pull/5834

**Pull request merged**
