### PR TITLE
CHANGELOG 5.3.0

### PR DESCRIPTION
**Pull request by Smjert**

### CODE REVIEW

**Comment by directionless** [comment]
FWIW I have tooling that generates these.

**Comment by Smjert** [comment]
> FWIW I have tooling that generates these.

Ah yeah I went by hand, it's not too difficult, the categorization has to be done by hand anyway.
What I have done is:
```
git log --oneline 5.2.3..HEAD
```
This gives an output like:
```
[...]
4ea9f2c73 Fix for gathering python packages from any user Python installations (#7414)
7bb36e889 Implement `output_size` for `osquery_schedule` (#7436)
fd529718e CHANGELOG 5.2.2 (#7447)
d0db86439 Bump mkdocs from 1.1.2 to 1.2.3 in /docs (#7457)
```
And from there, cleanup + categorization.

Finally for the number of contributors:
```
git shortlog --summary --numbered --email 5.2.3..HEAD
```
which results in:
```
     5  Alessandro Gario <5714290+alessandrogario@users.noreply.github.com>
     3  Jason Meller <jason@kolide.co>
     2  Joe Sweeney <joe.sweeney@trailofbits.com>
     1  Joe Sweeney <joseph.sweeney95@gmail.com>
     1  Mayur Shingote <mayur.shingote@yahoo.com>
     1  Nick Collier <48997416+nickcollier@users.noreply.github.com>
     1  Rajesh Pangare <44482451+raj3shp@users.noreply.github.com>
     6  Sharvil Shah <sharvil@sharvilshah.com>
    28  Stefano Bonicatti <stefano.bonicatti@gmail.com>
     1  dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
     6  iko1 <me@remotecpp.dev>
     1  np5 <eric@zentral.pro>
     3  seph <seph@directionless.org>
     1  yonnym <yonnym@gmail.com>
     1  zhupeijun <zhupeijun2009@gmail.com>
```
And removing the bot, plus a duplicate (same person, different mail) we get the result of 13 contribs until now.

**Review by zwass — APPROVED** [review]
:shipit:

**Comment by directionless** [comment]
> > FWIW I have tooling that generates these.
> 
> Ah yeah I went by hand, it's not too difficult, the categorization has to be done by hand anyway. What I have done is:

Yeah, in many ways it's a glorified `git log --oneline`, but it adds several features. 
* it aggregates non-squashed PRs. They happen sometimes, and having tooling helped. 
* it replace the github links of `#7575` with fill URLs, like `https://github.com/osquery/osquery/pull/7575`
* it supports rerunning to find any missed commits. (It keys this off the PR number)

Doing it manually isn't wrong, the results look fine. But so you know.

Anyhow, Zach approved this PR 👍

**Pull request merged**
