### PR TITLE
Link librdkafka on windows

### PR DESCRIPTION
**Pull request by herbmaster**
I fixed the issues left open in (https://github.com/osquery/osquery/pull/6095)

- CMake now also links librdkafka on windows
- Fixed the usage of the LIBRDKAFKA_STATICLIB macro

### CODE REVIEW

**Comment by herbmaster** [comment]
Looks like the the pipeline works differently than the instructions in (https://osquery.readthedocs.io/en/latest/development/building/)
I'll look into it after I sorted out the CLA with my company and update the request.

**Comment by herbmaster** [comment]
CLA is awaiting approval.
I was able to reproduce the issue using Ninja and your patched sccache version.
In my estimation, the is a bug in CMake not forwarding the target_compile_definitions correctly if Ninja is used as a generator. I will push an updated version, as the Ninja build works locally and I verified that Kafka SSL is working.

**Comment by theopolis** [comment]
> CLA is awaiting approval.

Let us know if you need anything, from a technical point of view you should be able to sign this automatically and the approval will update. If you have signed it and this PR has not updated, please let us know.

**Comment by phreatom** [comment]
> Let us know if you need anything, 
Hi, I have the honour to sign the CLA on behalf of our company and am struggling to get myself in the situation to be able to do so. I am waiting for support by the Linux Foundation. If you can help there, or know a shortcut please let me know.

**Comment by herbmaster** [comment]
I followed the CLA link and got the message that everything is okay, and that I need to refresh this page to see the updated status.
However, it still is red. I repeated it multiple times to no avail.
Do you have any suggestion on how to proceed?

**Comment by herbmaster** [comment]
Using a different browser didn't do the trick either :(

**Comment by Smjert** [comment]
Closing and reopening to see if EasyCLA gets pinged.

**Comment by Smjert** [comment]
> Using a different browser didn't do the trick either :(

Closing and reopening the PR seems to have worked :).
Sometimes I guess either Github or EasyCLA loses the trigger call.

**Pull request merged**
