### PR TITLE
Docs: Update the bug report issue template to mention BUILD.md

### PR DESCRIPTION
**Pull request by alessandrogario**

### CODE REVIEW

**Comment by theopolis** [comment]
Are we tracking the places we need to update to make the documentation relevant?

If we make this change we should also track where we need to reverse-update to remove debt.

**Comment by csicher** [comment]
?

**Comment by alessandrogario** [comment]
> Are we tracking the places we need to update to make the documentation relevant?
> 
> If we make this change we should also track where we need to reverse-update to remove debt.

I think the only thing we have left to update is the build page on the ReadTheDocs

**Comment by theopolis** [comment]
So instead of this change, should we update: https://github.com/osquery/osquery/blob/master/docs/wiki/development/building.md

**Comment by theopolis** [comment]
#5708 supersedes these changes.

**Pull request closed without merging**
