### PR TITLE
Fix for #5315. Ensure view recreated on startup

### PR DESCRIPTION
**Pull request by anjalichandnani**
Added flag to check if the views config is updated the first time, and if query already exists in the local db store, then all we need to do is create the view.
I don't understand why the views are stored in the local db, but have left those as is, and remedied only the issue.

### CODE REVIEW

**Comment by obelisk** [comment]
Good find and thanks for fixing this! I'll try and get this in as soon as I can.

**Comment by fmanco** [comment]
@achandnani-scwx I totally missed the DB removal step. Okay this LGTM then.

**Comment by theopolis** [comment]
Hi @anjalichandnani, I don't completely understand why this is needed but I am happy to spend more time deep-diving if we still want this.

Do you mind rebasing this against the current master and refactoring the code slightly so we are not duplicating calls to `CREATE VIEW`.

**Comment by anjalichandnani** [comment]
Hi @theopolis, I had forgotten about this, just as well the issue is captured https://github.com/osquery/osquery/issues/5315.
I will rebase and submit CL in a couple of days.

**Comment by anjalichandnani** [comment]
I had not set the right git user email, and the checkins are showing as my corp user account :-(
Going to start a new fork, and re-submit the CL... the couple of lines change is easier to re-do than reset the commits.

**Comment by anjalichandnani** [comment]
New pull request for same change: https://github.com/osquery/osquery/pull/5732

**Pull request closed without merging**
