### PR TITLE
refactor: Move ephemeral database plugin into core and simplify tests

### PR DESCRIPTION
**Pull request by theopolis**
One goal is to not have anything within "core" `./osquery` link against anything in `./plugins`. There are a few steps towards that but this seems to be the simplest.

### CODE REVIEW

**Comment by theopolis** [comment]
I am still on the path to solving https://github.com/osquery/osquery/issues/6397 and this PR is one step.

**Review by directionless — APPROVED** [review]
LGTM

**Comment by theopolis** [comment]
Thanks for the review. I will make one more change to this and request a review again (sorry about that).

**Comment by theopolis** [comment]
@directionless if you have a moment to review again, I made some minor clean up changes.

**Review by directionless — APPROVED** [review]
Seems fine. Not sure if it's all correct, but it doesn't seem like it will be problematic.

**Pull request merged**
