### PR TITLE
tables: Remove required-column warning message

### PR DESCRIPTION
**Pull request by theopolis**
It is no longer possible to check for missing required-columns in xFilter (see #6001). This removes the checking and applies nitpicks that may slightly improve speed.

### CODE REVIEW

**Comment by directionless** [comment]
I feel slightly sad if this is the only route available to us, but I also defer to your knowledge of this code.

**Comment by theopolis** [comment]
@packetzero May be more expert than me at these APIs and may know an alternative?

**Comment by terracatta** [comment]
@theopolis Will this also impact other warnings for example the warning thrown in the Curl table for issue #6034?

Does it impact other warnings like when you try to enumerate `chrome_extensions` running osquery as a root user? The message shown today is... 
> virtual_table.cpp:922] The chrome_extensions table returns data based on the current user by default, consider JOINing against the users table"

We definitely see a lot of value in these warning messages and we parse them out of the status logs and correlate them with distributed queries in our back-end so users get an understanding why they saw 0 rows returned.

Just trying to understand impact.

**Comment by theopolis** [comment]
> Will this also impact other warnings for example the warning thrown in the Curl table for issue #6034?

That bug report seems unrelated to this change.

> Does it impact other warnings like when you try to enumerate chrome_extensions running osquery as a root user?

Nope. Those user-based table warnings still exist.

After the office hours today, and @Smjert's comment on `SQLITE_CONSTRAINT` being transformed back into a `SQLITE_OK`, I'd like to take more time to understand if there's an alternative approach that maintains this warning. If I find one I will open a new PR for comparison.

**Comment by directionless** [comment]
> I'd like to take more time to understand if there's an alternative approach that maintains this warning. If I find one I will open a new PR for comparison.

Okay!  If you decide you want to cut  4.1.1, you can merge this and we can iterate. Or we can delay. I'm good with either

**Pull request closed without merging**
