### PR TITLE
Add patch for apache/thrift #5078

### LINKED ISSUE #4280: Windows Extension goes away if  "select * from pipes" query is issued.
Details are as follows - 
 1) Issue query "select * from pipes" from osquery shell or via scheduled queries.

2) This causes Extension Service responsible for communication with Extensions via pipe (\\.\pipe\shell.em) to exit.

3) Extension Watcher detects that shell.em no longer exists and throws following message 
I0412 01:20:24.826747  6708 extensions.cpp:208] Extension watcher ending: osquery core has gone away
and extension exits.

4) Osquery core is not able to restart extension again as it can not find  pipe -  \\.\pipe\shell.em

Possible Root cause is as follows -

Select * from pipes query logic opens all pipes present on the system (including shell.em) and reports its status in the query result. 
Opening a client pipe handle connects to the server pipe instance (which created shell.em pipe), which is served by thrift server for named pipes. Thrift server creates a thread for each client connection and if a client disconnects before thrift server offloads the new connection to a thread, an exception is thrown and the thrift server exits, resulting in a sequence of events -> shell.em is deleted-> extension exits->osquery cannot start extension again.

Though we observed this issue with our custom extension but issue can be reproduced with any extension.

Osquery Version - 2.11.2

### PR DESCRIPTION
**Pull request by theopolis**
Fixes #4280

@mike-myers-tob do you have a way to test this?

Generated from `apache/thrift` using:

```
git checkout e56f717b7f62ba5b1ace7382d728ac7f0fda940f
git format-patch -1 HEAD
```

### CODE REVIEW

**Comment by mike-myers-tob** [comment]
> Fixes #4280
> 
> @mike-myers-tob do you have a way to test this?

Sure I can build on a Windows VM, run osqueryi with an extension, and `select * from pipes;` and see if the osquery extension dies.

**Comment by directionless** [comment]
> > Fixes #4280
> > @mike-myers-tob do you have a way to test this?
> 
> Sure I can build on a Windows VM, run osqueryi with an extension, and `select * from pipes;` and see if the osquery extension dies.

Can also download the build from the GH artifacts :)

**Comment by mike-myers-tob** [comment]
> Can also download the build from the GH artifacts :)

Oh right! Well anyway, big success! The bug is gone:

```
PS C:\Projects\osquery\build> .\osquery\RelWithDebInfo\osqueryi.exe --allow_unsafe --disable_extensions=false --extension .\external\extension_trailofbits\RelWithDebInfo\trailofbits_osquery_extensions.ext.exe
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> SELECT * FROM HostDenylist;
+---------+---------------------------+--------------+----------------+-----------+
| address | domain                    | sinkhole     | firewall_block | dns_block |
+---------+---------------------------+--------------+----------------+-----------+
|         | bitbucket.corp.ncrypt.com | 10.130.21.63 |                | UNMANAGED |
+---------+---------------------------+--------------+----------------+-----------+
osquery> SELECT * FROM pipes;
+------+------------------------------------------------------------+-----------+---------------+-----------------------------------+
| pid  | name                                                       | instances | max_instances | flags                             |
+------+------------------------------------------------------------+-----------+---------------+-----------------------------------+
| 580  | InitShutdown                                               | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 680  | lsass                                                      | 4         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 660  | ntsvcs                                                     | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 660  | scerpc                                                     | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-2a8-0                       |           |               |                                   |
|      | Winsock2\CatalogChangeListener-3bc-0                       |           |               |                                   |
| 956  | epmapper                                                   | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-244-0                       |           |               |                                   |
| 1004 | LSM_API_service                                            | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-3ec-0                       |           |               |                                   |
| 1212 | atsvc                                                      | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 1256 | eventlog                                                   | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-4e8-0                       |           |               |                                   |
|      | Winsock2\CatalogChangeListener-4bc-0                       |           |               |                                   |
| 2684 | spoolss                                                    | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-a7c-0                       |           |               |                                   |
| 2788 | wkssvc                                                     | 4         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 3204 | trkwks                                                     | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 3248 | W32TIME_ALT                                                | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 3212 | srvsvc                                                     | 4         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-294-0                       |           |               |                                   |
| 3220 | vgauth-service                                             | 1         | 255           | PIPE_CLIENT_END,PIPE_TYPE_BYTE    |
| 3708 | ROUTER                                                     | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 7536 | MsFteWds                                                   | 5         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 7536 | SearchTextHarvester                                        | 1         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 8704 | PSHost.132563386211861334.8704.DefaultAppDomain.powershell | 1         | 1             | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER                     |           |               |                                   |
| 8832 | MSBuild8832                                                | 1         | 1             | PIPE_CLIENT_END,PIPE_TYPE_BYTE    |
| 6980 | MSBuild6980                                                | 1         | 1             | PIPE_CLIENT_END,PIPE_TYPE_BYTE    |
| 5464 | MSBuild5464                                                | 1         | 1             | PIPE_CLIENT_END,PIPE_TYPE_BYTE    |
| 4792 | shell.em                                                   | 1         | 255           | PIPE_CLIENT_END,PIPE_TYPE_BYTE    |
| 2236 | shell.em.2627                                              | 1         | 255           | PIPE_CLIENT_END,PIPE_TYPE_BYTE    |
+------+------------------------------------------------------------+-----------+---------------+-----------------------------------+
osquery> SELECT * FROM HostDenylist;
+---------+---------------------------+--------------+----------------+-----------+
| address | domain                    | sinkhole     | firewall_block | dns_block |
+---------+---------------------------+--------------+----------------+-----------+
|         | bitbucket.corp.ncrypt.com | 10.130.21.63 |                | UNMANAGED |
+---------+---------------------------+--------------+----------------+-----------+
```

**Review by mike-myers-tob — APPROVED** [review]
In testing on Windows, which is the only platform affected by this patch, the effect is that `select` from `pipes` table no longer crashes the extensions. Tested with osquery run as non-Administrator (standard user) and as Administrator. Tested also the effect of running SysInternals `Accesschk` (this used to crash the pipe, now it just returns safely the information about the pipe).

**Pull request merged**
