### PR TITLE
Fix for Potential memory leak in class ServiceArgumentParser's Constructor

### LINKED ISSUE #8351: Potential memory leak in class ServiceArgumentParser's Constructor
# Bug report

### What operating system and version are you using?
```
version = 10.0.22631
build = 22631
platform = windows
```
### What version of osquery are you using?
`version = 5.12.1`

### What steps did you take to reproduce the issue?
while working on the issue [#8310](https://github.com/osquery/osquery/issues/8310) , i was revieing my changes when i found this issue in the following file, [main.cpp](https://github.com/osquery/osquery/blob/master/osquery/main/windows/main.cpp) 

in the **ServiceArgumentParser** class's constructor
image

### What did you expect to see?
No memory leak

### What did you see instead?
Though i did not see anything but there is a potential for a memory leak

### PR DESCRIPTION
**Pull request by pradishmp**
Fixes #8351 

**What changed ?**
This is a corner case scenario where there is a potential for a memory leak. For this leak to occur, two things must happen:

1. The arguments passed to the service should be wide char strings.
2. The function call `toMBString`, which is used to convert the wide char strings to multibyte strings, should fail, returning a `nullptr`.

When a `nullptr ` is returned, as part of cleaning up the heap memory allocated, the `cleanArgs() `function is called. However, this function will only clean up the memory if the Boolean variable `owns_argv_ptr`s is set to true. In this case, as the variable is still false, the function will only remove all elements from the vector.

Later, when the Boolean variable `owns_argv_ptrs` is set to true and the destructor gets a chance to clean up, it cannot do anything as the elements are already removed and the vector size is zero.

Therefore, the fix is to remove the call to the function `clearArgs()` and leave it to the destructor to clean up the memory.

### CODE REVIEW

**Comment by zwass** [comment]
Reopen for CI fix

**Review by directionless — APPROVED** [review]
I think this is okay -- there's a destructer that clears the args. @Smjert @zwass either of you?

**Comment by michael-myers** [comment]
> I think this is okay -- there's a destructer that clears the args. @Smjert @zwass either of you?

Both before and after this PR, the same private method, `cleanArgs` will free the memory, only, it needs to be called only after `owns_argv_ptrs_ = true;`. Another way to fix this, maybe how I would do it, would be to set `owns_argv_ptrs_ = true;` immediately after the `CommandLineToArgvW` returns successfully. So, before the `for` loop instead of right after it. But this PR also fixes the issue.

**Comment by pradishmp** [comment]
i was trying to remove some of the older commits which are not related to this issue..ended up closing the PR, Apologies for the inconvenience caused. i can create a new PR and submit for review , please let me know your thoughts

**Comment by pradishmp** [comment]
> > I think this is okay -- there's a destructer that clears the args. @Smjert @zwass either of you?
> 
> Another way to fix this, maybe how I would do it, would be to set `owns_argv_ptrs_ = true;` immediately after the `CommandLineToArgvW` returns successfully. So, before the `for` loop instead of right after it. 

i too agree with this approach, freeing memory immediately rather than wait for the destructor also make sence,

**Comment by Smjert** [comment]
> i was trying to remove some of the older commits which are not related to this issue..ended up closing the PR, Apologies for the inconvenience caused. i can create a new PR and submit for review , please let me know your thoughts

Feel free to open a new PR, I suggest not using the `master` branch on your repo to submit the PR from, but a separate PR specific branch. This way you can track osquery `master` branch, work on your bugfix branch and also sync it against `master` with a rebase (don't use merge or be aware that git pull by default merges if it cannot do a fast forward merge, which can be changed).

**Comment by directionless** [comment]
@pradishmp We are likely to cut a release in the next few days, I don't know if the timing will line up on your next PR, but there will always be another release.

**Comment by pradishmp** [comment]
> @pradishmp We are likely to cut a release in the next few days, I don't know if the timing will line up on your next PR, but there will always be another release.

ok i will see if i can fix this today itself or we can always have this in next release, whichever works best for the product.

**Pull request closed without merging**
