### PR TITLE
Migrate glibc from "facebook" dependencies

### PR DESCRIPTION
**Pull request by zwass**

### CODE REVIEW

**Comment by zwass** [comment]
I'm not convinced that this is the appropriate way to handle this module considering there is nothing to build and it only adds linker flags. But this solution is only about as weird as the previous solution where it lived in the `facebook` modules.

Thoughts?

**Comment by Smjert** [comment]
This was again an attempt of being in sync with Buck.
Honestly, I would just move those flags in https://github.com/osquery/osquery/blob/master/cmake/flags.cmake, @alessandrogario thoughts?

**Comment by alessandrogario** [comment]
> This was again an attempt of being in sync with Buck.
> Honestly, I would just move those flags in https://github.com/osquery/osquery/blob/master/cmake/flags.cmake, @alessandrogario thoughts?

looks like a better approach :smile:

**Comment by theopolis** [comment]
@zwass, the CI errors are legit:
```
ld: library not found for -lthirdparty_glibc_pthread
```

**Pull request merged**
