### PR TITLE
Restore some tests that were not built

### PR DESCRIPTION
**Pull request by Smjert**
Some of the tests were missing from the build because they were not ported to the new code, and some of them were failing.

Now most of them have been restored, only one is missing (tls_config_tests), which I think needs some refactoring, together with the other TLS tests that are in the build but disabled.

### CODE REVIEW

**Comment by Smjert** [comment]
Rebased onto master.

**Comment by theopolis** [comment]
Heads up @fmanco, for any context on these tests.

**Comment by theopolis** [comment]
Let's go forward if you don't mind rebasing. Please feel free to merge-with-rebase if tests pass.

**Comment by Smjert** [comment]
Rebased onto master

**Pull request merged**
